# Generated by Django 3.2.5 on 2021-09-20 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('call_amount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_capital_calls', to='companies.company')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_capital_calls', to='companies.companyuser')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_capital_calls', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
