# Generated by Django 3.2.5 on 2021-09-20 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capital_calls', '0001_initial'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcall',
            name='fund_investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_capital_calls', to='investors.fundinvestor'),
        ),
    ]
