# Generated by Django 3.2.5 on 2021-10-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_calls', '0002_capitalcall_fund_investor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalcall',
            name='call_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
