# Generated by Django 3.2.16 on 2023-03-02 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funds', '0053_auto_20230210_1408'),
        ('documents', '0061_auto_20230302_0837'),
        ('companies', '0031_auto_20230129_1600'),
        ('capital_calls', '0003_alter_capitalcall_call_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundCapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_timestamp', models.DateField()),
                ('approved_at', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_calls_company', to='companies.company')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_calls_funds', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapitalCallDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('fulfilled_from_loan', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('investor_obligation', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('investment', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('management_fees', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('optimization_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('fund_expenses', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('total_to_date', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('capital_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_call_detail', to='capital_calls.fundcapitalcall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_call_user_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
