# Generated by Django 3.2.16 on 2023-03-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0025_alter_workflow_module'),
        ('capital_calls', '0004_capitalcalldetail_fundcapitalcall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundcapitalcall',
            options={'ordering': ('-created_timestamp',)},
        ),
        migrations.RenameField(
            model_name='capitalcalldetail',
            old_name='optimization_cost',
            new_name='organization_cost',
        ),
        migrations.AddField(
            model_name='fundcapitalcall',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundcapitalcall',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_capital_call', to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='fundcapitalcall',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
