# Generated by Django 3.2.16 on 2023-03-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0061_auto_20230302_0837'),
        ('capital_calls', '0005_auto_20230306_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcalldetail',
            name='notice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_call_notices', to='documents.document'),
        ),
        migrations.AddField(
            model_name='capitalcalldetail',
            name='partner_commitment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='capitalcalldetail',
            name='previously_contributed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='capitalcalldetail',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='capitalcalldetail',
            name='unpaid_commitment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='capitalcalldetail',
            name='capital_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_call_details', to='capital_calls.fundcapitalcall'),
        ),
    ]
