# Generated by Django 3.2.16 on 2023-03-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0061_auto_20230302_0837'),
        ('capital_calls', '0006_auto_20230309_0559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundcapitalcall',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='capitalcalldetail',
            name='notice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_call_detail', to='documents.document'),
        ),
    ]
