# Generated by Django 3.2.12 on 2022-03-25 04:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tax_records', '0008_auto_20220304_2330'),
        ('kyc_records', '0018_alter_kycrecord_unique_together'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='kyc_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='kyc_records.kycrecord'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tax_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tax_records.taxrecord'),
        ),
    ]
