# Generated by Django 3.2.12 on 2022-04-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20220325_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='max_leverage_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='max_leverage_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
