# Generated by Django 3.2.12 on 2022-04-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0037_auto_20220331_1040'),
        ('applications', '0003_auto_20220404_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='eligibility_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='eligibility_criteria.eligibilitycriteriaresponse'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='eligibility_response',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='eligibility_criteria.eligibilitycriteriaresponse'),
        ),
    ]
