# Generated by Django 3.2.12 on 2022-04-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20220407_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Submitted'), (3, 'Denied'), (4, 'Approved'), (5, 'Withdrawn')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Submitted'), (3, 'Denied'), (4, 'Approved'), (5, 'Withdrawn')], default=1),
        ),
    ]
