# Generated by Django 3.2.13 on 2022-04-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20220422_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='eligibility_response_data_migration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='eligibility_response_data_migration',
            field=models.BooleanField(default=False),
        ),
    ]
