# Generated by Django 3.2.13 on 2022-04-26 09:03

from django.db import migrations


def attach_eligibility_criteria_to_application(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    CompanyUser = apps.get_model('companies', 'CompanyUser')
    EligibilityCriteriaResponse = apps.get_model('eligibility_criteria', 'EligibilityCriteriaResponse')

    for application in Application.objects.all():
        if application.eligibility_response:
            continue

        company_user = CompanyUser.objects.get(user=application.user, company=application.company)

        try:
            latest_response = EligibilityCriteriaResponse.objects.filter(
                response_by=company_user,
                criteria__fund=application.fund
            ).latest('modified_at')
        except EligibilityCriteriaResponse.DoesNotExist:
            continue

        application.eligibility_response = latest_response
        application.eligibility_response_data_migration = True
        application.save()


def reverse_attach_eligibility_criteria_to_application(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    Application.objects.filter(
        eligibility_response_data_migration=True
    ).update(
        eligibility_response_data_migration=False,
        eligibility_response=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ('applications', '0007_auto_20220426_0918'),
    ]

    operations = [
        migrations.RunPython(
            attach_eligibility_criteria_to_application,
            reverse_code=reverse_attach_eligibility_criteria_to_application
        ),
    ]
