# Generated by Django 3.2.12 on 2022-04-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('applications', '0008_auto_20220426_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='payments.paymentdetail'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='payment_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.paymentdetail'),
        ),
    ]
