# Generated by Django 3.2.13 on 2022-04-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0030_auto_20220427_1841'),
        ('applications', '0008_auto_20220426_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='share_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.fundshareclass'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='share_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='funds.fundshareclass'),
        ),
    ]
