# Generated by Django 3.2.13 on 2022-04-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20220426_1658'),
        ('applications', '0009_auto_20220427_1841'),
    ]

    operations = [
    ]
