# Generated by Django 3.2.13 on 2022-04-28 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0014_workflow_sub_module'),
        ('applications', '0010_merge_0009_auto_20220426_1658_0009_auto_20220427_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='workflow',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflows.workflow'),
        ),
    ]
