# Generated by Django 3.2.13 on 2022-05-11 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20220429_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocumentsRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_name', models.TextField()),
                ('document_description', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
