# Generated by Django 3.2.13 on 2022-05-12 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0013_applicationdocumentsrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocumentsrequests',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Pending'), (3, 'Submitted'), (4, 'Approved')], default=1),
        ),
        migrations.CreateModel(
            name='HistoricalApplicationDocumentsRequests',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Pending'), (3, 'Submitted'), (4, 'Approved')], default=1)),
                ('document_name', models.TextField()),
                ('document_description', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical application documents requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
