# Generated by Django 3.2.13 on 2022-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20220512_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_data_protection_policy_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='is_data_protection_policy_agreed',
            field=models.BooleanField(default=False),
        ),
    ]
