# Generated by Django 3.2.13 on 2022-06-14 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_auto_20220608_0924'),
        ('applications', '0014_auto_20220512_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.companyfundvehicle'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='vehicle',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.companyfundvehicle'),
        ),
    ]
