# Generated by Django 3.2.13 on 2022-06-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20220512_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_application_updated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='update_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='is_application_updated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='update_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
