# Generated by Django 3.2.13 on 2022-06-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20220614_0648'),
        ('applications', '0016_auto_20220607_2022'),
    ]

    operations = [
    ]
