# Generated by Django 3.2.13 on 2022-06-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_auto_20220527_0836'),
        ('applications', '0017_merge_0015_auto_20220614_0648_0016_auto_20220607_2022'),
    ]

    operations = [
    ]
