# Generated by Django 3.2.13 on 2022-06-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_auto_20220622_0952'),
        ('applications', '0018_merge_20220615_1759'),
    ]

    operations = [
    ]
