# Generated by Django 3.2.13 on 2022-07-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_userapplicationstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplicationstate',
            name='module',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Eligibility Criteria'), (2, 'KYC Record'), (3, 'Tax Record'), (4, 'Banking Details'), (5, 'Fund Documents'), (6, 'Requested Documents'), (7, 'Investment Allocation'), (8, 'Participant'), (9, 'Agreement'), (10, 'Power of Attorney Document')]),
        ),
    ]
