# Generated by Django 3.2.13 on 2022-07-19 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0021_auto_20220427_1841'),
        ('applications', '0022_alter_userapplicationstate_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_applications', to='investors.investor'),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='investor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='investors.investor'),
        ),
    ]
