# Generated by Django 3.2.15 on 2022-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_applicationcompanydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcompanydocument',
            name='envelope_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
