# Generated by Django 3.2.15 on 2022-08-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_applicationcompanydocument_envelope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcompanydocument',
            name='gp_signing_complete',
            field=models.BooleanField(default=False),
        ),
    ]
