# Generated by Django 3.2.15 on 2022-09-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_applicationcompanydocument_gp_signing_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationcompanydocument',
            options={'ordering': ('created_at',)},
        ),
    ]
