# Generated by Django 3.2.15 on 2022-09-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_auto_20220909_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='restricted_geographic_area',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='restricted_time_period',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='restricted_geographic_area',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='restricted_time_period',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
