# Generated by Django 3.2.15 on 2022-10-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_auto_20220923_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
