# Generated by Django 3.2.15 on 2022-10-31 10:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0032_auto_20221003_0926'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='application',
            managers=[
                ('active_applications', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalapplication',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
