# Generated by Django 3.2.15 on 2022-11-23 09:20

from django.db import migrations


def update_applicant_company_documents(apps, schema_editor):
    ApplicationCompanyDocument = apps.get_model('applications', 'ApplicationCompanyDocument')
    CompanyUser = apps.get_model('companies', 'CompanyUser')
    application_company_documents = ApplicationCompanyDocument.objects.filter(
        signed_document__uploaded_by_user__isnull=True
    )
    for application_document in application_company_documents:
        document = application_document.signed_document
        if not document:
            continue
        application = application_document.application
        document.uploaded_by_user = CompanyUser.objects.get(company=application.company, user=application.user)
        document.save()


class Migration(migrations.Migration):
    dependencies = [
        ('applications', '0032_auto_20221003_0926'),
    ]

    operations = [
        migrations.RunPython(update_applicant_company_documents, reverse_code=migrations.RunPython.noop),
    ]
