# Generated by Django 3.2.15 on 2022-11-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0054_auto_20221007_0734'),
        ('applications', '0033_auto_20221123_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcompanydocument',
            name='certificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_document_certificates', to='documents.document'),
        ),
    ]
