# Generated by Django 3.2.15 on 2022-11-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0033_auto_20221031_1031'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='application',
            managers=[
            ],
        ),
    ]
