# Generated by Django 3.2.15 on 2022-11-28 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_alter_application_managers'),
        ('applications', '0034_applicationcompanydocument_certificate'),
    ]

    operations = [
    ]
