# Generated by Django 3.2.15 on 2022-12-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_remove_task_task_document'),
        ('applications', '0035_merge_20221128_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcompanydocument',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_company_document', to='workflows.task'),
        ),
    ]
