# Generated by Django 3.2.16 on 2023-02-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0046_auto_20221111_0016'),
        ('payments', '0003_auto_20220627_1541'),
        ('tax_records', '0014_auto_20221104_1631'),
        ('applications', '0037_auto_20230117_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='kyc_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='kyc_records.kycrecord'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_details', to='payments.paymentdetail'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tax_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='tax_records.taxrecord'),
        ),
    ]
