# Generated by Django 3.2.16 on 2023-03-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax_records', '0014_auto_20221104_1631'),
        ('kyc_records', '0046_auto_20221111_0016'),
        ('applications', '0038_auto_20230222_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='kyc_record',
            field=models.ForeignKey(help_text='KyC Record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='kyc_records.kycrecord'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tax_record',
            field=models.ForeignKey(help_text='Tax Record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='tax_records.taxrecord'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='kyc_record',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='KyC Record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kyc_records.kycrecord'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='tax_record',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Tax Record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tax_records.taxrecord'),
        ),
    ]
