# Generated by Django 3.2.16 on 2023-03-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0039_auto_20230320_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcompanydocument',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
