# Generated by Django 3.2.16 on 2023-03-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0039_auto_20230313_1626'),
        ('applications', '0039_auto_20230320_1347'),
    ]

    operations = [
    ]
