# Generated by Django 3.2.16 on 2023-03-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0040_applicationcompanydocument_deleted'),
        ('applications', '0040_merge_0039_auto_20230313_1626_0039_auto_20230320_1347'),
    ]

    operations = [
    ]
