# Generated by Django 3.2.18 on 2023-05-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0041_auto_20230510_1943'),
        ('applications', '0041_merge_20230329_1642'),
    ]

    operations = [
    ]
