# Generated by Django 3.2.11 on 2022-02-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20220203_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='section',
            field=models.CharField(default='question/bank_account_information', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='section',
            field=models.CharField(default='question/bank_account_information', max_length=256),
            preserve_default=False,
        ),
    ]
