# Generated by Django 3.2.12 on 2022-04-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20220215_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Updated'), (3, 'Resolved')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Updated'), (3, 'Resolved')], default=1),
        ),
    ]
