# Generated by Django 3.2.13 on 2022-05-27 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20220512_0847'),
        ('companies', '0016_auto_20220503_1836'),
        ('kyc_records', '0029_merge_20220425_1419'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0005_auto_20220404_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalApplicationComment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('text', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Updated'), (3, 'Resolved')], default=1)),
                ('module', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eligibility Criteria'), (2, 'KYC Record'), (3, 'Tax Record'), (4, 'Banking Details'), (5, 'Fund Documents')], db_index=True, null=True)),
                ('module_id', models.PositiveIntegerField(db_index=True)),
                ('question_identifier', models.CharField(db_index=True, max_length=250)),
                ('document_identifier', models.CharField(max_length=250)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('application', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='applications.application')),
                ('comment_for', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('commented_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kyc_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='kyc_records.kycrecord')),
            ],
            options={
                'verbose_name': 'historical application comment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Updated'), (3, 'Resolved')], default=1)),
                ('module', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eligibility Criteria'), (2, 'KYC Record'), (3, 'Tax Record'), (4, 'Banking Details'), (5, 'Fund Documents')], db_index=True, null=True)),
                ('module_id', models.PositiveIntegerField(db_index=True)),
                ('question_identifier', models.CharField(db_index=True, max_length=250)),
                ('document_identifier', models.CharField(max_length=250)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_comments', to='applications.application')),
                ('comment_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_comments', to=settings.AUTH_USER_MODEL)),
                ('commented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('kyc_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_record_comments', to='kyc_records.kycrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
