# Generated by Django 3.2.13 on 2022-05-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_applicationcomment_historicalapplicationcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcomment',
            name='document_identifier',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplicationcomment',
            name='document_identifier',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
