# Generated by Django 3.2.13 on 2022-05-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20220530_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationcomment',
            name='module',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eligibility Criteria'), (2, 'KYC Record'), (3, 'Tax Record'), (4, 'Banking Details'), (5, 'Fund Documents'), (6, 'Requested Documents')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalapplicationcomment',
            name='module',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Eligibility Criteria'), (2, 'KYC Record'), (3, 'Tax Record'), (4, 'Banking Details'), (5, 'Fund Documents'), (6, 'Requested Documents')], db_index=True, null=True),
        ),
    ]
