# Generated by Django 3.2.5 on 2021-09-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('transaction_date', models.DateTimeField()),
                ('activity_type', models.CharField(db_index=True, max_length=250)),
                ('investor_id', models.CharField(db_index=True, max_length=250)),
                ('investor_code', models.CharField(db_index=True, max_length=250)),
                ('investor_name', models.CharField(db_index=True, max_length=250)),
                ('investment_entity_id', models.CharField(db_index=True, max_length=250)),
                ('investment_code', models.CharField(db_index=True, max_length=250)),
                ('investment_name', models.CharField(db_index=True, max_length=250)),
                ('loan_only', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('equity', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('outstanding_commitment', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('escrow_balance', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('interest_balance', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('interest_repay_income', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('employee_repay_income', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('income_distributions', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('interest_repay_capital', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('employee_repay_capital', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('capital_distributions', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('distributions_recallable', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('fair_value_adjustment', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('leveraged_irr', models.FloatField(default=0)),
                ('unleveraged_irr', models.FloatField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_activities', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
