# Generated by Django 3.2.5 on 2021-09-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20210927_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanactivity',
            old_name='investment_entity_id',
            new_name='investment_code',
        ),
        migrations.AddField(
            model_name='fundactivity',
            name='gain_loss',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
