# Generated by Django 3.2.5 on 2021-09-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20210928_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundactivity',
            old_name='investment_code',
            new_name='fund_id',
        ),
        migrations.RenameField(
            model_name='loanactivity',
            old_name='investment_code',
            new_name='fund_id',
        ),
        migrations.RemoveField(
            model_name='fundactivity',
            name='investment_name',
        ),
        migrations.RemoveField(
            model_name='fundactivity',
            name='investor_code',
        ),
        migrations.RemoveField(
            model_name='fundactivity',
            name='investor_name',
        ),
    ]
