# Generated by Django 3.2.5 on 2021-09-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20210930_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundactivity',
            old_name='investor_id',
            new_name='investor_vehicle_id',
        ),
        migrations.RenameField(
            model_name='loanactivity',
            old_name='investor_id',
            new_name='investor_vehicle_id',
        ),
    ]
