# Generated by Django 3.2.5 on 2021-10-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20211011_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundactivity',
            name='equity_called_to_date',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='fundactivity',
            name='equity_commitment',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='loanactivity',
            name='interest_paid_to_date',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='loanactivity',
            name='loan_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
