# Generated by Django 3.2.5 on 2021-10-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20211014_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundactivity',
            name='capital_distributions',
        ),
        migrations.RemoveField(
            model_name='fundactivity',
            name='distributions_recallable',
        ),
        migrations.RemoveField(
            model_name='fundactivity',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='fundactivity',
            name='escrow_balance',
        ),
        migrations.RemoveField(
            model_name='loanactivity',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='loanactivity',
            name='employee_repay_capital',
        ),
        migrations.RemoveField(
            model_name='loanactivity',
            name='employee_repay_income',
        ),
        migrations.RemoveField(
            model_name='loanactivity',
            name='loan_only',
        ),
    ]
