# Generated by Django 3.2.5 on 2021-10-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20211021_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundactivity',
            name='distributions_since_inception',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
