# Generated by Django 3.2.5 on 2021-11-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_fundactivity_gross_share_of_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundactivity',
            name='fund_ownership',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=13),
        ),
    ]
