# Generated by Django 3.2.5 on 2021-11-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_alter_fundactivity_fund_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundactivity',
            name='capital_distributions_since_inception',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='fundactivity',
            name='capital_distributions_since_last_nav',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='fundactivity',
            name='income_distributions_since_inception',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='fundactivity',
            name='income_distributions_since_last_nav',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
