# Generated by Django 3.2.5 on 2021-11-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20211110_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundactivity',
            name='fund_ownership',
            field=models.FloatField(default=0),
        ),
    ]
