# Generated by Django 3.2.5 on 2021-11-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_alter_fundactivity_fund_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundactivity',
            name='leverage_ratio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fundactivity',
            name='raw_investment_product_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fundactivity',
            name='share_class',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
