# Generated by Django 3.2.5 on 2021-11-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_auto_20211124_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanactivity',
            name='leverage_ratio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='loanactivity',
            name='raw_investment_product_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='loanactivity',
            name='share_class',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
