# Generated by Django 3.2.5 on 2021-11-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_auto_20211124_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundactivity',
            name='capital_distributions_since_inception',
        ),
        migrations.RemoveField(
            model_name='fundactivity',
            name='capital_distributions_since_last_nav',
        ),
        migrations.RemoveField(
            model_name='fundactivity',
            name='income_distributions_since_inception',
        ),
        migrations.RemoveField(
            model_name='fundactivity',
            name='income_distributions_since_last_nav',
        ),
    ]
