# Generated by Django 3.2.12 on 2022-03-21 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0017_fundinvestor_gross_distributions_recallable_to_date'),
        ('funds', '0024_auto_20220303_1712'),
        ('companies', '0013_alter_companyuser_unique_together'),
        ('activities', '0021_fundactivity_gross_distributions_recallable_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('partner_id', models.CharField(max_length=250)),
                ('effective_date', models.DateTimeField()),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(0, 'Unknown Transaction Type'), (1, 'Contribution Bridging Loan'), (2, 'Contribution Escrow'), (3, 'Contribution Escrow Paydown'), (4, 'Contribution Loan'), (5, 'Contribution'), (6, 'Distribution Dividend Capital Gain'), (7, 'Distribution Dividend Loan Repay Capital'), (8, 'Distribution Dividend Loan Repay Income'), (9, 'Distribution Dividend Income'), (10, 'Distribution Dividend Interest Repay Capital'), (11, 'Distribution Dividend Interest Repay Income'), (12, 'Fair Value Adjustment'), (13, 'Initial Commitment'), (14, 'Interest'), (15, 'Late Fee Charged'), (16, 'Late Fee Payment')])),
                ('actual_transaction_amount', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('prorated_transaction_amount', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_transaction_details', to='companies.company')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transaction_details', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_transaction_details', to='investors.investor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transactiondetail',
            constraint=models.UniqueConstraint(fields=('company', 'partner_id'), name='unique_company_detail'),
        ),
    ]
