# Generated by Django 3.2.12 on 2022-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0023_alter_transactiondetail_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetail',
            name='transaction_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Finalized')], default=1),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='transaction_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown Transaction Type'), (1, 'Contribution Bridging Loan'), (2, 'Contribution Escrow'), (3, 'Contribution Escrow Paydown'), (4, 'Contribution Loan'), (5, 'Contribution'), (6, 'Distribution Dividend Capital Gain'), (7, 'Distribution Dividend Loan Repay Capital'), (8, 'Distribution Dividend Loan Repay Income'), (9, 'Distribution Dividend Income'), (10, 'Distribution Dividend Interest Repay Capital'), (11, 'Distribution Dividend Interest Repay Income'), (12, 'Fair Value Adjustment'), (13, 'Initial Commitment'), (14, 'Interest'), (15, 'Late Fee Charged'), (16, 'Late Fee Payment'), (17, 'Contribution Recallable Distribution'), (18, 'Distribution Dividend Loan Repay Redemption'), (19, 'Distribution Dividend Interest Repay Redemption'), (20, 'Distribution Dividend Recallable'), (21, 'Follow on Commitment'), (22, 'Redemption')], default=0),
        ),
    ]
