# Generated by Django 3.2.12 on 2022-03-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_auto_20220322_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='effective_date',
            field=models.DateField(),
        ),
    ]
