# Generated by Django 3.2.12 on 2022-03-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0025_alter_transactiondetail_effective_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='prorated_transaction_amount',
        ),
    ]
