# Generated by Django 3.2.13 on 2022-04-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0026_remove_transactiondetail_prorated_transaction_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transactiondetail',
            name='unique_company_detail',
        ),
        migrations.AddConstraint(
            model_name='transactiondetail',
            constraint=models.UniqueConstraint(fields=('company', 'partner_id', 'investor_id', 'fund_id', 'transaction_type', 'effective_date'), name='unique_transaction_detail'),
        ),
    ]
