# Generated by Django 3.2.5 on 2021-09-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='commitment_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='gross_share_of_investment_product',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='loan_commitment',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='unpaid_interest',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='investor',
            name='vehicle_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individual'), (2, 'Entity')], default=1),
        ),
    ]
