# Generated by Django 3.2.5 on 2021-09-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('investors', '0002_auto_20210928_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_fund_investors', to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='fundinvestor',
            name='gain',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
