# Generated by Django 3.2.5 on 2021-09-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_auto_20210928_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='called_to_date',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
