# Generated by Django 3.2.5 on 2021-09-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_fundinvestor_called_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundinvestor',
            name='percent_of_account',
        ),
    ]
