# Generated by Django 3.2.5 on 2021-10-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0005_remove_fundinvestor_percent_of_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='vehicle_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Entity')], null=True),
        ),
    ]
