# Generated by Django 3.2.5 on 2021-10-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0008_alter_investor_investor_account_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='loan_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
