# Generated by Django 3.2.5 on 2021-12-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0016_auto_20211209_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestor',
            name='gross_distributions_recallable_to_date',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
