# Generated by Django 3.2.13 on 2022-04-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0028_fundvehicle'),
        ('companies', '0014_auto_20220404_1635'),
        ('investors', '0017_fundinvestor_gross_distributions_recallable_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorSharedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('leverage', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_shared_classes', to='companies.company')),
                ('fund_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_shared_classes', to='funds.fundvehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='investor',
            name='shared_classes',
            field=models.ManyToManyField(to='investors.InvestorSharedClass'),
        ),
    ]
