# Generated by Django 3.2.13 on 2022-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0018_alter_investor_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='vehicle_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Entity')], null=True),
        ),
    ]
