# Generated by Django 3.2.13 on 2022-04-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0018_auto_20220421_0701'),
        ('investors', '0019_alter_investor_vehicle_type'),
    ]

    operations = [
    ]
