# Generated by Django 3.2.16 on 2022-12-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0024_alter_fundinvestor_nav_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinvestor',
            name='nav_share',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=21),
        ),
    ]
