export const QUALIFIED_PURCHASER_BLOCK_ID = 'US-QP' // 3
export const AU_WHOLESALE_CLIENT = 'AU-WC' // 4
export const AU_PROFESSIONAL_INVESTOR_BLOCKS = 'AU-PI' // 5
export const AU_SOPHISTICATED_INVESTOR = 'AU-SI' // 6
export const CN_LEGITIMATE_ASSETS = 'CN-LOA' // 7
export const CN_TAX_FILINGS_ID = 'CN-TF' // 8
export const FILLING_ACKNOWLEDGEMENT_ID = 'KR-FA' // 9
export const JP_ELIGIBLE_ENTITY = 'JP-EE' // 10
export const SG_ACCREDITED_INVESTOR = 'SG-AI'
export const SG_QUALIFYING_PERSON = 'SG-QP'

export const GENERIC_BLOCK_CODES = [
	AU_WHOLESALE_CLIENT,
	AU_PROFESSIONAL_INVESTOR_BLOCKS,
	AU_SOPHISTICATED_INVESTOR,
	SG_ACCREDITED_INVESTOR,
	SG_QUALIFYING_PERSON,
	CN_LEGITIMATE_ASSETS,
	CN_TAX_FILINGS_ID,
	JP_ELIGIBLE_ENTITY,
	FILLING_ACKNOWLEDGEMENT_ID,
	QUALIFIED_PURCHASER_BLOCK_ID,
]

export const US_ACCREDITED_INVESTOR = 'US-AI' // 1
export const KNOWLEDGEABLE_EMPLOYEE = 'KE' // 2
export const HK_ELIGIBILITY_BLOCK = 'HK-EB'

export const PREVIEW_GENERIC_BLOCK_CODE = [
	...GENERIC_BLOCK_CODES,
	KNOWLEDGEABLE_EMPLOYEE,
	HK_ELIGIBILITY_BLOCK,
	US_ACCREDITED_INVESTOR,
]

export const APPROVAL_CHECKBOXES = 'AC'
export const KEY_INVESTMENT_INFORMATION = 'KII'
export const KR_REVERSE_INQUIRY = 'KR-RI'
export const SG_INVESTMENT_PROFESSIONAL = 'SG-IP'

export const CHECKBOX_BLOCKS = [SG_INVESTMENT_PROFESSIONAL]
