# Generated by Django 3.2.5 on 2021-12-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eligibility_criteria', '0001_initial'),
        ('geographics', '0001_initial'),
        ('companies', '0008_auto_20211109_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundcriteriaregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_criteria', to='geographics.region'),
        ),
        migrations.AddField(
            model_name='fundcriteriacountry',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_criteria', to='geographics.country'),
        ),
        migrations.AddField(
            model_name='fundcriteriacountry',
            name='fund_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_countries', to='eligibility_criteria.fundeligibilitycriteria'),
        ),
        migrations.AddField(
            model_name='criteriareviewer',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_reviewers', to='eligibility_criteria.fundeligibilitycriteria'),
        ),
        migrations.AddField(
            model_name='criteriareviewer',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser'),
        ),
        migrations.AddField(
            model_name='criteriablockgroupconnector',
            name='from_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_connected_to', to='eligibility_criteria.criteriablock'),
        ),
        migrations.AddField(
            model_name='criteriablockgroupconnector',
            name='to_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_connected_from', to='eligibility_criteria.criteriablock'),
        ),
        migrations.AddField(
            model_name='criteriablockgroup',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_block_groups', to='eligibility_criteria.fundeligibilitycriteria'),
        ),
        migrations.AddField(
            model_name='criteriablockfiles',
            name='criteria_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eligibility_criteria.criteriablock'),
        ),
        migrations.AddField(
            model_name='criteriablockconnector',
            name='from_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_connected_to', to='eligibility_criteria.criteriablock'),
        ),
        migrations.AddField(
            model_name='criteriablockconnector',
            name='to_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_connected_from', to='eligibility_criteria.criteriablock'),
        ),
        migrations.AddField(
            model_name='criteriablock',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eligibility_criteria.block'),
        ),
        migrations.AddField(
            model_name='criteriablock',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eligibility_criteria.fundeligibilitycriteria'),
        ),
        migrations.AddField(
            model_name='criteriablock',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_blocks', to='eligibility_criteria.criteriablockgroup'),
        ),
        migrations.AddField(
            model_name='blockcategory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_block_categories', to='companies.company'),
        ),
        migrations.AddField(
            model_name='block',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_blocks', to='eligibility_criteria.blockcategory'),
        ),
        migrations.AddField(
            model_name='block',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_blocks', to='companies.company'),
        ),
    ]
