# Generated by Django 3.2.5 on 2021-12-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundeligibilitycriteria',
            name='is_published',
        ),
        migrations.AddField(
            model_name='fundeligibilitycriteria',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundeligibilitycriteria',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Pending Approval'), (3, 'Published')], default=1),
        ),
    ]
