# Generated by Django 3.2.5 on 2021-12-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0003_auto_20211207_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundeligibilitycriteria',
            name='investor_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Entity')], null=True),
        ),
    ]
