# Generated by Django 3.2.5 on 2021-12-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0004_alter_fundeligibilitycriteria_investor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='admin_uploaded_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='has_checkboxes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
