# Generated by Django 3.2.5 on 2021-12-09 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0006_auto_20211209_0943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CriteriaBlockFiles',
            new_name='CriteriaBlockDocument',
        ),
    ]
