# Generated by Django 3.2.5 on 2021-12-10 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0007_rename_criteriablockfiles_criteriablockdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CriteriaBlockDocument',
        ),
    ]
