# Generated by Django 3.2.5 on 2021-12-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0008_delete_criteriablockdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriablock',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
