# Generated by Django 3.2.5 on 2021-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0009_criteriablock_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriablock',
            name='is_user_documents_step',
            field=models.BooleanField(default=False),
        ),
    ]
