# Generated by Django 3.2.11 on 2022-01-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
        ('eligibility_criteria', '0012_auto_20220118_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundeligibilitycriteria',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_eligibility_criteria', to='workflows.workflow'),
        ),
    ]
