# Generated by Django 3.2.11 on 2022-01-25 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_task_unique_together'),
        ('eligibility_criteria', '0013_fundeligibilitycriteria_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundeligibilitycriteria',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_eligibility_criteria', to='workflows.workflow'),
        ),
    ]
