# Generated by Django 3.2.11 on 2022-02-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0014_alter_fundeligibilitycriteria_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
