# Generated by Django 3.2.11 on 2022-02-02 09:32

from django.db import migrations


def delete_old_accredited_investor_block(apps, schema_editor):
    Block = apps.get_model('eligibility_criteria', 'Block')
    Block.objects.filter(heading='Apply Accredited Investor Rules').delete()


def add_block_id(apps, schema_editor):
    Block = apps.get_model('eligibility_criteria', 'Block')
    block_id_mapping = {
        'US Accredited Investor Rules': 'US-AI',
        'Approval Checkboxes': 'AC',
        'Knowledgeable Employee': 'KE',
        'Key Investment Information': 'KII',
    }
    for block in Block.objects.all():
        block_id = block_id_mapping[block.heading]
        block.block_id = block_id
        block.save()


class Migration(migrations.Migration):
    dependencies = [
        ('eligibility_criteria', '0015_block_block_id'),
    ]

    operations = [
        migrations.RunPython(delete_old_accredited_investor_block),
        migrations.RunPython(add_block_id)
    ]
