# Generated by Django 3.2.11 on 2022-02-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_companyuser_unique_together'),
        ('eligibility_criteria', '0016_auto_20220202_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('company', 'category', 'block_id')},
        ),
    ]
