# Generated by Django 3.2.11 on 2022-02-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0017_auto_20220202_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
