# Generated by Django 3.2.11 on 2022-02-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_companyuser_unique_together'),
        ('eligibility_criteria', '0019_block_is_admin_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCriteriaResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eligibility_criteria.fundeligibilitycriteria')),
                ('response_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CriteriaBlockResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('response_json', models.JSONField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eligibility_criteria.criteriablock')),
                ('criteria_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eligibility_criteria.eligibilitycriteriaresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
