# Generated by Django 3.2.12 on 2022-02-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_document_type'),
        ('eligibility_criteria', '0021_auto_20220213_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseBlockDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_response_blocks', to='documents.document')),
                ('response_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_block_documents', to='eligibility_criteria.criteriablockresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
