# Generated by Django 3.2.12 on 2022-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0022_responseblockdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='last_position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
