# Generated by Django 3.2.12 on 2022-02-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0023_eligibilitycriteriaresponse_last_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='is_knowledgeable',
            field=models.BooleanField(default=False),
        ),
    ]
