# Generated by Django 3.2.12 on 2022-02-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20220224_1910'),
        ('eligibility_criteria', '0025_auto_20220222_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibilitycriteriaresponse',
            name='applicant_info',
        ),
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_criteria_responses', to='cards.workflow'),
        ),
    ]
