# Generated by Django 3.2.12 on 2022-03-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0005_alter_kycrecord_tax_country'),
        ('eligibility_criteria', '0026_auto_20220227_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibilitycriteriaresponse',
            name='workflow',
        ),
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='kyc_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_eligibility_criteria_responses', to='kyc_records.kycrecord'),
        ),
    ]
