# Generated by Django 3.2.12 on 2022-03-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0027_auto_20220301_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('leverage_ratio', models.FloatField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ApplicantInfo',
        ),
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='investment_amount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eligibility_criteria.investmentamount'),
        ),
    ]
