# Generated by Django 3.2.12 on 2022-03-13 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eligibility_criteria', '0028_auto_20220301_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentamount',
            name='final_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='final_leverage_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='HistoricalInvestmentAmount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('leverage_ratio', models.FloatField(default=0)),
                ('final_amount', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('final_leverage_ratio', models.FloatField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical investment amount',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
