# Generated by Django 3.2.12 on 2022-03-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_alter_workflow_workflow_type'),
        ('eligibility_criteria', '0028_auto_20220301_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='review_workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow'),
        ),
    ]
