# Generated by Django 3.2.12 on 2022-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0029_eligibilitycriteriaresponse_review_workflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eligibilitycriteriaresponse',
            old_name='review_workflow',
            new_name='workflow',
        ),
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='is_financial',
            field=models.BooleanField(default=False),
        ),
    ]
