# Generated by Django 3.2.12 on 2022-03-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0011_auto_20220316_0752'),
        ('eligibility_criteria', '0030_auto_20220316_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eligibilitycriteriaresponse',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eligibility_response', to='workflows.workflow'),
        ),
    ]
