# Generated by Django 3.2.12 on 2022-03-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0029_auto_20220313_1338'),
        ('eligibility_criteria', '0031_auto_20220316_1703'),
    ]

    operations = [
    ]
