# Generated by Django 3.2.12 on 2022-03-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0032_merge_0029_auto_20220313_1338_0031_auto_20220316_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitycriteriaresponse',
            name='investment_amount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_criteria_response', to='eligibility_criteria.investmentamount'),
        ),
    ]
