# Generated by Django 3.2.12 on 2022-03-29 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0005_alter_countryiddocumenttype_id_document_type'),
        ('eligibility_criteria', '0032_merge_0029_auto_20220313_1338_0031_auto_20220316_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_blocks', to='geographics.country'),
        ),
        migrations.AddField(
            model_name='block',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_blocks', to='geographics.region'),
        ),
    ]
