# Generated by Django 3.2.12 on 2022-03-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0033_auto_20220329_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundeligibilitycriteria',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fundeligibilitycriteria',
            name='name',
        ),
    ]
