# Generated by Django 3.2.12 on 2022-03-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0033_alter_eligibilitycriteriaresponse_investment_amount'),
        ('eligibility_criteria', '0034_auto_20220329_1050'),
    ]

    operations = [
    ]
