# Generated by Django 3.2.12 on 2022-03-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0035_merge_20220330_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundeligibilitycriteria',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Pending Approval'), (3, 'Approved'), (4, 'Published')], default=1),
        ),
    ]
