# Generated by Django 3.2.12 on 2022-03-31 10:40

from django.db import migrations

from api.eligibility_criteria.models import FundEligibilityCriteria


def update_eligibility_criteria_published(apps, schema_editor):
    EligibilityCriteria = apps.get_model('eligibility_criteria', 'FundEligibilityCriteria')
    EligibilityCriteria.objects.filter(
        status=FundEligibilityCriteria.CriteriaStatusChoice.APPROVED.value
    ).update(status=FundEligibilityCriteria.CriteriaStatusChoice.PUBLISHED.value)


def reverse_eligibility_criteria_published(apps, schema_editor):
    EligibilityCriteria = apps.get_model('eligibility_criteria', 'FundEligibilityCriteria')
    EligibilityCriteria.objects.filter(
        status=FundEligibilityCriteria.CriteriaStatusChoice.PUBLISHED.value
    ).update(status=FundEligibilityCriteria.CriteriaStatusChoice.APPROVED.value)


class Migration(migrations.Migration):
    dependencies = [
        ('eligibility_criteria', '0036_alter_fundeligibilitycriteria_status'),
    ]

    operations = [
        migrations.RunPython(
            update_eligibility_criteria_published,
            reverse_code=reverse_eligibility_criteria_published
        ),
    ]
