# Generated by Django 3.2.12 on 2022-03-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0037_auto_20220331_1040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EligibilityCriteriaReviewer',
        ),
    ]
