# Generated by Django 3.2.12 on 2022-04-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0038_eligibilitycriteriaresponse_is_self_certified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundeligibilitycriteria',
            name='investor_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Participant'), (3, 'ENTITY'), (4, 'Private Company'), (5, 'Limited Partnership'), (6, 'Trust')], null=True),
        ),
    ]
