# Generated by Django 3.2.13 on 2022-04-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0038_eligibilitycriteriaresponse_is_self_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriablock',
            name='auto_completed',
            field=models.BooleanField(default=False),
        ),
    ]
