# Generated by Django 3.2.13 on 2022-04-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0038_delete_eligibilitycriteriareviewer'),
        ('eligibility_criteria', '0039_criteriablock_auto_completed'),
    ]

    operations = [
    ]
