# Generated by Django 3.2.13 on 2022-04-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0039_alter_fundeligibilitycriteria_investor_type'),
        ('eligibility_criteria', '0039_criteriablock_auto_completed'),
    ]

    operations = [
    ]
