# Generated by Django 3.2.13 on 2022-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0040_merge_20220421_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundeligibilitycriteria',
            name='investor_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Individual'), (2, 'Entity')], null=True),
        ),
    ]
