# Generated by Django 3.2.13 on 2022-04-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0040_merge_20220420_1543'),
        ('eligibility_criteria', '0041_alter_fundeligibilitycriteria_investor_type'),
    ]

    operations = [
    ]
