# Generated by Django 3.2.15 on 2022-08-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0047_alter_customsmartblockfield_reviewers_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eligibilitycriteriaresponse',
            name='investment_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_criteria_response', to='eligibility_criteria.investmentamount'),
        ),
    ]
