# Generated by Django 3.2.13 on 2022-09-02 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0048_alter_eligibilitycriteriaresponse_investment_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customsmartblock',
            unique_together={('eligibility_criteria', 'title')},
        ),
    ]
