# Generated by Django 3.2.13 on 2022-09-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0049_alter_customsmartblock_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsmartblockfield',
            options={'ordering': ('created_at',)},
        ),
    ]
