# Generated by Django 3.2.15 on 2022-12-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0051_fundeligibilitycriteria_expression_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriablock',
            name='is_custom_logic_block',
            field=models.BooleanField(default=False),
        ),
    ]
