# Generated by Django 3.2.15 on 2023-01-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0054_auto_20221214_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmentamount',
            name='final_leverage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvestmentamount',
            name='total_investment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='final_leverage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='total_investment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
