# Generated by Django 3.2.16 on 2023-02-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0056_auto_20230125_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundeligibilitycriteria',
            name='is_smart_criteria',
            field=models.BooleanField(default=False),
        ),
    ]
