# Generated by Django 3.2.16 on 2023-03-28 10:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0057_fundeligibilitycriteria_is_smart_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsmartblockfield',
            name='reviewers_required',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Financial Eligibility Reviewer', 'Financial Eligibility Reviewer'), ('Knowledgeable Employee Eligibility Reviewer', 'Knowledgeable Eligibility Reviewer'), ('No Review Required', 'No Review Required')], max_length=120), blank=True, default=list, size=None),
        ),
    ]
