# Generated by Django 3.2.13 on 2023-03-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0058_alter_customsmartblockfield_reviewers_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsmartblock',
            name='is_multiple_selection_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
