# Generated by Django 3.2.18 on 2023-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0059_customsmartblock_is_multiple_selection_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycriteriaresponse',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
