# Generated by Django 3.2.18 on 2023-05-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0060_eligibilitycriteriaresponse_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestmentamount',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentamount',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
