# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
 testsuite_smoke_testrail:
    working_directory: ~/circleci-marketplace-api
    resource_class: large
    docker:
      - image: cypress/included:10.6.0
        user: root
        environment:
          TERM: xterm
      - image: cimg/postgres:13.3
        environment:
          POSTGRES_USER: citest
          POSTGRES_DB: citest
          POSTGRES_PASSWORD: citest
      - image: localstack/localstack
      - image: cimg/redis:6.2
    steps:
      - checkout
      - run:
          name: Running Smoke tests
          command: |
            cd frontend
            npm i
            CYPRESS_TESTRAIL_REPORTER_USERNAME=$TESTRAIL_REPORTING_USER CYPRESS_TESTRAIL_REPORTER_PASSWORD=$TESTRAIL_REPORTING_PASSWORD CIRCLE_BUILD_ID=$CIRCLE_SHA1 CYPRESS_USERNAME=$CYPRESS_USERNAME CYPRESS_PASSWORD=$CYPRESS_PASSWORD npm run cy:adminSmokeTestRail || true
           
 testsuite_smoke_testrail2:
    working_directory: ~/circleci-marketplace-api
    resource_class: large
    docker:
      - image: cypress/included:10.6.0
        user: root
        environment:
          TERM: xterm
      - image: cimg/postgres:13.3
        environment:
          POSTGRES_USER: citest
          POSTGRES_DB: citest
          POSTGRES_PASSWORD: citest
      - image: localstack/localstack
      - image: cimg/redis:6.2
    steps:
      - checkout
      - run:
          name: Running Smoke tests
          command: |
            cd frontend
            npm i
            CYPRESS_TESTRAIL_REPORTER_USERNAME=$TESTRAIL_REPORTING_USER CYPRESS_TESTRAIL_REPORTER_PASSWORD=$TESTRAIL_REPORTING_PASSWORD CIRCLE_BUILD_ID=$CIRCLE_SHA1 CYPRESS_USERNAME=$CYPRESS_USERNAME CYPRESS_PASSWORD=$CYPRESS_PASSWORD npm run cy:adminSmokeTestRail || true
           

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows



workflows:
  continuous-deploy:
    jobs:
      - testsuite_smoke_testrail:
  daily:
    triggers:
      - schedule:
          cron: "* 1 * * *"
          filters:
            branches:
              only:
                - main            
    jobs:
      - testsuite_smoke_testrail
