# Generated by Django 3.2.13 on 2022-05-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0012_auto_20220429_0912'),
        ('funds', '0031_merge_20220427_2052'),
        ('companies', '0016_auto_20220503_1836'),
        ('documents', '0027_funddocument_document_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAgreementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_agreement_documents', to='companies.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_agreement', to='documents.document')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_agreement_documents', to='funds.fund')),
            ],
            options={
                'unique_together': {('company', 'fund', 'document')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=120)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_witnesses', to='applications.application')),
            ],
            options={
                'unique_together': {('email', 'application')},
            },
        ),
        migrations.CreateModel(
            name='ApplicantAgreementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('envelope_id', models.CharField(max_length=80, unique=True)),
                ('agreement_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_document_applicants', to='agreements.fundagreementdocument')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_agreements', to='applications.application')),
                ('signed_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_document', to='documents.document')),
            ],
            options={
                'unique_together': {('agreement_document', 'application')},
            },
        ),
        migrations.CreateModel(
            name='AgreementDocumentWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('envelope_id', models.CharField(max_length=80, unique=True)),
                ('applicant_agreement_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_witnesses', to='agreements.applicantagreementdocument')),
                ('signed_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='witness_document', to='documents.document')),
                ('witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_agreements', to='agreements.applicationwitness')),
            ],
            options={
                'unique_together': {('witness', 'applicant_agreement_document')},
            },
        ),
    ]
