# Generated by Django 3.2.13 on 2022-05-19 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20220429_0912'),
        ('documents', '0029_alter_document_document_type'),
        ('agreements', '0003_auto_20220516_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementdocumentwitness',
            name='certificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_witness_document', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='agreementdocumentwitness',
            name='applicant_agreement_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_witnesses', to='agreements.applicantagreementdocument'),
        ),
        migrations.AlterField(
            model_name='applicationwitness',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_witnesses', to='applications.application'),
        ),
    ]
