# Generated by Django 3.2.13 on 2022-05-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20220429_0912'),
        ('agreements', '0004_auto_20220519_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementdocumentwitness',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agreementdocumentwitness',
            name='applicant_agreement_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_witness', to='agreements.applicantagreementdocument'),
        ),
        migrations.AlterField(
            model_name='applicationwitness',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_witness', to='applications.application'),
        ),
    ]
