# Generated by Django 3.2.13 on 2022-07-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_auto_20220523_2007'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicantagreementdocument',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='applicantagreementdocument',
            name='agreement_document',
        ),
    ]
