# Generated by Django 3.2.13 on 2022-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0007_auto_20220705_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantagreementdocument',
            name='gp_signing_complete',
            field=models.BooleanField(default=False),
        ),
    ]
