# Generated by Django 3.2.13 on 2022-08-30 12:40

from django.db import migrations


def get_company_user(apps, application):
    CompanyUser = apps.get_model('companies', 'CompanyUser')
    return CompanyUser.objects.get(
        company=application.company,
        user=application.user
    )


def update_agreement_documents(apps, schema_editor):
    Document_model = apps.get_model('documents', 'Document')
    ApplicantAgreementDocument = apps.get_model('agreements', 'ApplicantAgreementDocument')
    Application = apps.get_model('applications', 'Application')
    applications = Application.objects.all()
    for application in applications:
        user = get_company_user(apps, application)
        agreements = ApplicantAgreementDocument.objects.filter(application=application, signed_document__isnull=False)
        agreement_ids = [agreement.signed_document.id for agreement in agreements]
        Document_model.objects.filter(
            id__in=agreement_ids,
            uploaded_by_user__isnull=True
        ).update(uploaded_by_user=user)



class Migration(migrations.Migration):
    dependencies = [
        ('agreements', '0008_applicantagreementdocument_gp_signing_complete'),
    ]

    operations = [
        migrations.RunPython(update_agreement_documents)
    ]
