# Generated by Django 3.2.15 on 2022-11-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0009_auto_20220830_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantagreementdocument',
            name='envelope_id',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
