# Generated by Django 3.2.13 on 2022-11-24 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_remove_task_task_document'),
        ('agreements', '0010_alter_applicantagreementdocument_envelope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantagreementdocument',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signing_task', to='workflows.task'),
        ),
    ]
