# Generated by Django 3.2.15 on 2022-11-23 12:40

from django.db import migrations


def update_agreement_documents(apps, schema_editor):
    ApplicantAgreementDocument = apps.get_model('agreements', 'ApplicantAgreementDocument')
    CompanyUser = apps.get_model('companies', 'CompanyUser')
    application_agreement_documents = ApplicantAgreementDocument.objects.filter(
        certificate__uploaded_by_user__isnull=True
    )
    for application_agreement_document in application_agreement_documents:
        certificate = application_agreement_document.certificate
        application = application_agreement_document.application
        if not certificate:
            continue
        certificate.uploaded_by_user = CompanyUser.objects.get(company=application.company, user=application.user)
        certificate.save()


class Migration(migrations.Migration):
    dependencies = [
        ('agreements', '0010_alter_applicantagreementdocument_envelope_id'),
    ]

    operations = [
        migrations.RunPython(update_agreement_documents, reverse_code=migrations.RunPython.noop),
    ]
