# Generated by Django 3.2.13 on 2022-11-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0011_applicantagreementdocument_task'),
        ('agreements', '0011_auto_20221123_1240'),
    ]

    operations = [
    ]
