# Generated by Django 3.2.15 on 2022-12-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_remove_task_task_document'),
        ('agreements', '0012_merge_20221124_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantagreementdocument',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_document', to='workflows.task'),
        ),
    ]
