# Generated by Django 3.2.18 on 2023-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0013_alter_applicantagreementdocument_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantagreementdocument',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
