# Generated by Django 3.2.18 on 2023-05-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0014_applicantagreementdocument_deleted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicantagreementdocument',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='applicantagreementdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('agreement_document', 'application'), name='unique_agreement_document_application_validation'),
        ),
    ]
