ADMIN_GROUP_NAME = "Full Access Admin"
APPROVER_GROUP_NAME = "Full Access Approver"
READONLY_GROUP_NAME = "Full Access Read Only"

FINANCIAL_ELIGIBILITY_REVIEWER = 'Financial Eligibility Reviewer'
KNOWLEDGEABLE_ELIGIBILITY_REVIEWER = 'Knowledgeable Employee Eligibility Reviewer'
EXTERNAL_REVIEWER = 'External Reviewer'
INTERNAL_TAX_REVIEWER = 'Internal Tax Reviewer'
ALLOCATION_REVIEWER = 'Allocation Reviewer'
AGREEMENT_REVIEWER = 'Agreement Reviewer'
GENERAL_PARTNER_SIGNER = 'General Partner Signer'
CAPITAL_CALL_REVIEWER = 'Capital Call Reviewer'
DISTRIBUTION_NOTICE_REVIEWER = 'Distribution Notice Reviewer'
NO_REVIEW_REQUIRED = 'No Review Required'

GROUPS = [ADMIN_GROUP_NAME, APPROVER_GROUP_NAME, READONLY_GROUP_NAME]

REVIEWER_GROUPS = [
    FINANCIAL_ELIGIBILITY_REVIEWER,
    KNOWLEDGEABLE_ELIGIBILITY_REVIEWER,
    EXTERNAL_REVIEWER,
    INTERNAL_TAX_REVIEWER,
    ALLOCATION_REVIEWER,
    AGREEMENT_REVIEWER
]

HAS_FULL_ADMIN_ACCESS_CODE, HAS_FULL_ADMIN_ACCESS_NAME = ("has_full_admin_access", "Has full admin access")
HAS_FULL_APPROVER_ACCESS_CODE, HAS_FULL_APPROVER_ACCESS_NAME = ("has_full_approver_access", "Has full approver access")
HAS_FULL_READONLY_ACCESS_CODE, HAS_FULL_READONLY_ACCESS_NAME = ("has_full_readonly_access", "Has full readonly access")
CAN_ONBOARD_INVESTOR_CODE, CAN_ONBOARD_INVESTOR_NAME = ("can_onboard_investor", "Can onboard an investor")
CAN_CREATE_INVESTMENT_CODE, CAN_CREATE_INVESTMENT_NAME = ("can_create_investment_fund", "Can create investment fund")
CAN_DEFINE_INTEREST_CODE, CAN_DEFINE_INTEREST_NAME = (
    "can_define_interest_indication",
    "Can define Interest Indication"
)
CAN_DEFINE_EC_CODE, CAN_DEFINE_EC_NAME = ("can_define_eligibility_criteria", "Can define Eligibility Criteria")

CAN_REVIEW_KNOWLEDGE_ELIGIBILITY_CODE, CAN_REVIEW_KNOWLEDGE_ELIGIBILITY_NAME = (
    "can_review_knowledge_eligibility",
    "Can review knowledge eligibility"
)

CAN_REVIEW_FINANCIAL_ELIGIBILITY_CODE, CAN_REVIEW_FINANCIAL_ELIGIBILITY_NAME = (
    "can_review_financial_eligibility",
    "Can review financial eligibility"
)

PERMISSIONS = [
    (HAS_FULL_ADMIN_ACCESS_CODE, HAS_FULL_ADMIN_ACCESS_NAME),
    (HAS_FULL_APPROVER_ACCESS_CODE, HAS_FULL_APPROVER_ACCESS_NAME),
    (HAS_FULL_READONLY_ACCESS_CODE, HAS_FULL_READONLY_ACCESS_NAME),
    (CAN_ONBOARD_INVESTOR_CODE, CAN_ONBOARD_INVESTOR_NAME),
    (CAN_CREATE_INVESTMENT_CODE, CAN_CREATE_INVESTMENT_NAME),
    (CAN_DEFINE_INTEREST_CODE, CAN_DEFINE_INTEREST_NAME),
    (CAN_DEFINE_EC_CODE, CAN_DEFINE_EC_NAME),
]

REVIEWER_PERMISSIONS = [
    (CAN_REVIEW_KNOWLEDGE_ELIGIBILITY_CODE, CAN_REVIEW_KNOWLEDGE_ELIGIBILITY_NAME),
    (CAN_REVIEW_FINANCIAL_ELIGIBILITY_CODE, CAN_REVIEW_FINANCIAL_ELIGIBILITY_NAME)
]

GROUP_TO_PERMISSION_CODE_MAP = {
    ADMIN_GROUP_NAME: HAS_FULL_ADMIN_ACCESS_CODE,
    APPROVER_GROUP_NAME: HAS_FULL_APPROVER_ACCESS_CODE,
    READONLY_GROUP_NAME: HAS_FULL_READONLY_ACCESS_CODE,
}

REVIEWER_GROUP_TO_PERMISSION_CODE_MAP = {
    ADMIN_GROUP_NAME: HAS_FULL_ADMIN_ACCESS_CODE,
    APPROVER_GROUP_NAME: HAS_FULL_APPROVER_ACCESS_CODE,
    READONLY_GROUP_NAME: HAS_FULL_READONLY_ACCESS_CODE,
}
