# Generated by Django 3.2.12 on 2022-02-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_companyuser_unique_together'),
        ('cards', '0002_alter_card_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkflow',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company'),
        ),
        migrations.AddField(
            model_name='historicalworkflow',
            name='slug',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='slug',
            field=models.CharField(default='asdas', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='card',
            name='workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.workflow'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalworkflow',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalworkflow',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Know Your Customer'), (2, 'Elegibility'), (3, 'Indication Of Interes')]),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Know Your Customer'), (2, 'Elegibility'), (3, 'Indication Of Interes')]),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('workflow', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='workflow',
            unique_together={('company', 'slug'), ('company', 'name')},
        ),
    ]
