# Generated by Django 3.2.12 on 2022-02-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20220215_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
