# Generated by Django 3.2.12 on 2022-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20220224_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_repeatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='is_repeatable',
            field=models.BooleanField(default=False),
        ),
    ]
