# Generated by Django 3.2.12 on 2022-03-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20220323_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_dependencies',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='card_dependencies',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='historicalcard',
            name='card_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('workflow', 'name', 'card_id')},
        ),
    ]
