# Generated by Django 3.2.12 on 2022-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20220323_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='kyc_investor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individual'), (2, 'Participant'), (3, 'ENTITY'), (4, 'Private Company'), (5, 'Limited Partnership')], null=True),
        ),
        migrations.AlterField(
            model_name='historicalcard',
            name='kyc_investor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individual'), (2, 'Participant'), (3, 'ENTITY'), (4, 'Private Company'), (5, 'Limited Partnership')], null=True),
        ),
    ]
