# Generated by Django 3.2.13 on 2022-05-09 07:28

from django.db import migrations
from slugify import slugify

from api.cards.utils import get_fund_kyc_workflow_name
from api.constants.kyc_investor_types import KYCInvestorType


def get_type_from_name(name: str):
    name = name.lower()
    if 'partnership' in name:
        return KYCInvestorType.LIMITED_PARTNERSHIP.name
    if 'private company' in name:
        return KYCInvestorType.PRIVATE_COMPANY.name
    if 'trust' in name:
        return KYCInvestorType.TRUST.name
    return None


def update_workflow_names(apps, schema_editor):
    Workflow = apps.get_model('cards', 'Workflow')
    for workflow in Workflow.objects.all():
        workflow_type = get_type_from_name(workflow.name)
        if not workflow_type:
            continue
        name = get_fund_kyc_workflow_name(
            company=workflow.company,
            vehicle_type=workflow_type

        )
        workflow.name = name
        workflow.slug = slugify(name)
        workflow.save()


class Migration(migrations.Migration):
    dependencies = [
        ('cards', '0009_auto_20220421_1218'),
    ]

    operations = [
        migrations.RunPython(update_workflow_names, reverse_code=migrations.RunPython.noop),

    ]
