# Generated by Django 3.2.13 on 2022-05-11 03:22

from django.db import migrations

from api.constants.kyc_investor_types import KYCInvestorType


def delete_extra_partnership_card(apps, schema_editor):
    Card = apps.get_model('cards', 'Card')
    Card.objects.filter(
        card_id='aml-kyc-limited-partnership-card-private-company-documents',
        kyc_investor_type=KYCInvestorType.LIMITED_PARTNERSHIP,
        name='Entity Information'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_auto_20220509_0728'),
    ]

    operations = [
        migrations.RunPython(delete_extra_partnership_card, reverse_code=migrations.RunPython.noop),
    ]
