US_ACCREDITED_INVESTOR_ID = 'US-AI'
APPROVAL_CHECKBOX_ID = 'AC'
KNOWLEDGE_EMPLOYEE_ID = 'KE'
KEY_INVESTMENT_INFORMATION_ID = 'KII'
AU_WHOLESALE_CLIENT_ID = 'AU-WC'
AU_SOPHISTICATED_INVESTOR_ID = 'AU-SI'
AU_PROFESSIONAL_INVESTOR_BLOCKS_ID = 'AU-PI'
SG_ACCREDITED_INVESTOR_ID = 'SG-AI'
SG_INVESTMENT_PROFESSIONAL_ID = 'SG-IP'
SG_QUALIFYING_PERSON_ID = 'SG-QP'
CN_LEGITIMATE_ASSETS_ID = 'CN-LOA'
CN_TAX_FILINGS_ID = 'CN-TF'
JP_ELIGIBLE_ENTITY_ID = 'JP-EE'
KR_REVERSE_INQUIRY_ID = 'KR-RI'
FILLING_ACKNOWLEDGEMENT_ID = 'KR-FA'
HONG_KONG_BLOCK_ID = 'HK-EB'
NO_LOCAL_REQUIREMENT_BLOCK_ID = 'NLC'
QUALIFIED_PURCHASER_BLOCK_ID = 'US-QP'


SINGLE_OPTION_BLOCKS = [
    AU_WHOLESALE_CLIENT_ID,
    AU_PROFESSIONAL_INVESTOR_BLOCKS_ID,
    AU_SOPHISTICATED_INVESTOR_ID,
    SG_ACCREDITED_INVESTOR_ID,
    SG_QUALIFYING_PERSON_ID,
    CN_LEGITIMATE_ASSETS_ID,
    CN_TAX_FILINGS_ID,
    JP_ELIGIBLE_ENTITY_ID,
    FILLING_ACKNOWLEDGEMENT_ID,
    KNOWLEDGE_EMPLOYEE_ID,
    US_ACCREDITED_INVESTOR_ID,
    HONG_KONG_BLOCK_ID,
    QUALIFIED_PURCHASER_BLOCK_ID
]

CHECKBOX_BLOCKS = [
    SG_INVESTMENT_PROFESSIONAL_ID
]

I_AGREE_BLOCKS = [
    KEY_INVESTMENT_INFORMATION_ID
]
