# Generated by Django 3.2.13 on 2022-04-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='ach',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='wires',
        ),
    ]
