# Generated by Django 3.2.13 on 2022-06-27 15:41

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20220428_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='credit_account_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='credit_account_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='reference',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=120, null=True),
        ),
    ]
