# Generated by Django 3.2.18 on 2023-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220627_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
