# Generated by Django 3.2.16 on 2023-02-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0037_auto_20230117_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=120)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='applications.application')),
            ],
            options={
                'db_table': 'application_backups',
            },
        ),
    ]
