# Generated by Django 3.2.11 on 2022-01-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('workflow', 'assigned_to')},
        ),
    ]
