# Generated by Django 3.2.11 on 2022-01-27 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
        ('workflows', '0003_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_tasks', to='admin_users.adminuser'),
        ),
    ]
