# Generated by Django 3.2.11 on 2022-01-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_task_requestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Review Request'), (2, 'Changes Requested'), (3, 'Publish')], default=1),
        ),
    ]
