# Generated by Django 3.2.11 on 2022-01-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_task_task_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
