# Generated by Django 3.2.12 on 2022-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Review'), (2, 'Response Review')]),
        ),
    ]
