# Generated by Django 3.2.12 on 2022-03-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_auto_20220307_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_workflow', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='step',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
