# Generated by Django 3.2.12 on 2022-03-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_companyuser_unique_together'),
        ('funds', '0024_auto_20220303_1712'),
        ('workflows', '0010_auto_20220308_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='associated_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_workflows', to='companies.companyuser'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_workflows', to='funds.fund'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='module',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Eligibility'), (2, 'Indication Of Interest'), (3, 'AML/KYC'), (4, 'User On-boarding')]),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_workflows', to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='workflow_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Review'), (2, 'Response Review'), (3, 'User Response')]),
        ),
    ]
