# Generated by Django 3.2.12 on 2022-03-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_auto_20220314_1313'),
        ('workflows', '0011_auto_20220316_0752'),
    ]

    operations = [
    ]
