# Generated by Django 3.2.12 on 2022-04-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0013_auto_20220328_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='sub_module',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
