# Generated by Django 3.2.13 on 2022-07-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0017_alter_workflow_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Review'), (2, 'Response Review'), (3, 'User Response'), (4, 'Application Allocation')]),
        ),
    ]
