# Generated by Django 3.2.13 on 2022-07-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0018_alter_workflow_workflow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='module',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Eligibility'), (2, 'Indication Of Interest'), (3, 'AML/KYC'), (4, 'User On-boarding'), (5, 'Tax Record'), (6, 'Agreements'), (7, 'Allocation'), (8, 'GP_SIGNING')]),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='workflow_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Review'), (2, 'Response Review'), (3, 'User Response'), (4, 'Application Allocation'), (5, 'APPLICATION_DOCUMENTS_SIGNING')]),
        ),
    ]
