# Generated by Django 3.2.15 on 2022-09-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0019_auto_20220715_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='module',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Eligibility'), (2, 'Indication Of Interest'), (3, 'AML/KYC'), (4, 'User On-boarding'), (5, 'Tax Record'), (6, 'Agreements'), (7, 'Allocation'), (8, 'GP Signing')]),
        ),
    ]
