# Generated by Django 3.2.13 on 2022-11-22 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0010_alter_applicantagreementdocument_envelope_id'),
        ('workflows', '0021_alter_workflow_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_document', to='agreements.applicantagreementdocument'),
        ),
    ]
