# Generated by Django 3.2.13 on 2022-11-24 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0022_task_task_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_document',
        ),
    ]
