# Generated by Django 3.2.15 on 2023-01-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_remove_task_task_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='module',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Eligibility'), (2, 'Indication Of Interest'), (3, 'AML/KYC'), (4, 'User On-boarding'), (5, 'Tax Record'), (6, 'Agreements'), (7, 'Allocation'), (8, 'GP Signing'), (9, 'Internal Tax Review')], db_index=True),
        ),
    ]
