# Generated by Django 3.2.16 on 2023-03-13 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0006_auto_20230103_1142'),
        ('workflows', '0024_alter_workflow_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='admin_users.adminuser')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='workflows.task')),
            ],
            options={
                'unique_together': {('task', 'admin')},
            },
        ),
    ]
