# Generated by Django 3.2.16 on 2023-03-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0006_auto_20230103_1142'),
        ('workflows', '0025_taskpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(through='workflows.TaskPermission', to='admin_users.AdminUser'),
        ),
        migrations.AlterModelTable(
            name='taskpermission',
            table='task_admins',
        ),
    ]
