# Generated by Django 3.2.18 on 2023-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0026_alter_workflow_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
