# Generated by Django 3.2.16 on 2023-03-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0025_alter_workflow_module'),
        ('workflows', '0026_auto_20230313_1656'),
    ]

    operations = [
    ]
