# Generated by Django 3.2.18 on 2023-05-10 20:25

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0027_auto_20230510_1935'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workflow',
            managers=[
                ('nested_workflows', django.db.models.manager.Manager()),
            ],
        ),
    ]
