# Generated by Django 3.2.16 on 2023-03-22 17:33

from django.db import migrations, models
import django.db.models.deletion


def load_approvers(apps, schema_editor):
    Task = apps.get_model('workflows', "Task")
    tasks = Task.objects.filter(status=2, completed=True)  # hardcoded because I can't retrieve the constant from here
    for t in tasks:
        t.approver = t.assigned_to
        t.save()


def unload_approvers(apps, schema_editor):
    Task = apps.get_model('workflows', "Task")
    tasks = Task.objects.filter(approver__isnull=False)
    for t in tasks:
        t.approver = None
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0006_auto_20230103_1142'),
        ('workflows', '0027_merge_20230320_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tasks', to='admin_users.adminuser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(help_text='Admin users assigned for this task', through='workflows.TaskPermission', to='admin_users.AdminUser'),
        ),
        migrations.AlterField(
            model_name='taskpermission',
            name='admin',
            field=models.ForeignKey(help_text='Admin authorized to manage the task', on_delete=django.db.models.deletion.DO_NOTHING, to='admin_users.adminuser'),
        ),
        migrations.AlterField(
            model_name='taskpermission',
            name='task',
            field=models.ForeignKey(help_text='Task related being authorized', on_delete=django.db.models.deletion.DO_NOTHING, to='workflows.task'),
        ),
        migrations.RunPython(load_approvers, unload_approvers)
    ]
