# Generated by Django 3.2.16 on 2023-03-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0026_alter_workflow_module'),
        ('workflows', '0028_auto_20230322_1733'),
    ]

    operations = [
    ]
