# Generated by Django 3.2.18 on 2023-05-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0028_alter_workflow_managers'),
        ('workflows', '0031_auto_20230502_1917'),
    ]

    operations = [
    ]
