from api.activities.models import TransactionDetail


LOAN_REPAY_TRANSACTION_TYPES = (
    TransactionDetail.TransactionDetailType.DISTRIBUTION_DIVIDEND_LOAN_REPAY_INCOME,
    TransactionDetail.TransactionDetailType.DISTRIBUTION_DIVIDEND_LOAN_REPAY_CAPITAL,
)

INTEREST_REPAY_TRANSACTION_TYPES = (
    TransactionDetail.TransactionDetailType.DISTRIBUTION_DIVIDEND_INTEREST_REPAY_CAPITAL,
    TransactionDetail.TransactionDetailType.DISTRIBUTION_DIVIDEND_INTEREST_REPAY_INCOME,
)

CONTRIBUTION_LOAN_TRANSACTION_TYPES = (
    TransactionDetail.TransactionDetailType.CONTRIBUTION_LOAN,
)

INTEREST_TRANSACTIONS = (
    TransactionDetail.TransactionDetailType.INTEREST,
)

TRANSACTION_GROUPS = (
    LOAN_REPAY_TRANSACTION_TYPES,
    INTEREST_REPAY_TRANSACTION_TYPES,
    CONTRIBUTION_LOAN_TRANSACTION_TYPES
)

ACCEPTABLE_TRANSACTION_TYPES = (
    *CONTRIBUTION_LOAN_TRANSACTION_TYPES,
    *INTEREST_REPAY_TRANSACTION_TYPES,
    *INTEREST_TRANSACTIONS,
    *LOAN_REPAY_TRANSACTION_TYPES
)
