# Generated by Django 3.2.5 on 2021-10-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='rate_date',
            field=models.DateTimeField(),
        ),
    ]
