# Generated by Django 3.2.12 on 2022-04-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0017_fundinvestor_gross_distributions_recallable_to_date'),
        ('documents', '0022_alter_document_document_type'),
        ('interest_statements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorInterestStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('statement_date', models.DateField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_interest_statements', to='investors.investor')),
            ],
            options={
                'unique_together': {('investor', 'statement_date')},
            },
        ),
    ]
