# Generated by Django 3.2.5 on 2021-12-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20211109_1041'),
        ('geographics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_code',
            field=models.CharField(default='EU', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('company', 'region_code')},
        ),
    ]
