# Generated by Django 3.2.12 on 2022-02-25 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0002_auto_20211207_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryIdDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id_document_type', models.PositiveSmallIntegerField(choices=[(1, 'Passport'), (2, "Driver's license"), (3, 'SSN card')])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='geographics.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
