# Generated by Django 3.2.13 on 2022-07-01 11:48
from api.geographics.data.us_states import US_STATES
from django.db import migrations


def create_states(apps, schema_editor):
    USState = apps.get_model('geographics', 'USState')
    for state in US_STATES:
        USState.objects.get_or_create(
            name=state['name'],
            iso_code=state['abbreviation']
        )

class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0006_usstates'),
    ]

    operations = [
        migrations.RunPython(create_states),
    ]
