# Generated by Django 3.2.13 on 2022-08-12 19:04

from django.db import migrations


def update_countries(apps, schema_editor):
    Country = apps.get_model('geographics', 'Country')
    Country.objects.filter(iso_code__in=['CU', 'IR', 'KP', 'RU']).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('geographics', '0007_auto_20220701_1148'),
    ]

    operations = [
        migrations.RunPython(update_countries),
    ]
