# Generated by Django 3.2.5 on 2021-09-20 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_initial'),
        ('funds', '0001_initial'),
        ('capital_calls', '0002_capitalcall_fund_investor'),
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notification_type', models.PositiveSmallIntegerField(choices=[(1, 'New Investment'), (2, 'Capital Call'), (3, 'Purchase Offer'), (4, 'Quarterly Statement'), (5, 'Purchase Confirmation')])),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('capital_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_call_notification', to='capital_calls.capitalcall')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_notifications', to='investors.investor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_user_notifications', to='companies.companyuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
