# Generated by Django 3.2.5 on 2021-11-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20211002_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Investment'), (2, 'Capital Call'), (3, 'Purchase Offer'), (4, 'Quarterly Statement'), (5, 'Purchase Confirmation'), (6, 'Prospectus'), (7, 'Agreement'), (8, 'Interest Statement'), (9, 'Nav Statement'), (10, 'Pitch Book'), (11, 'Tax'), (12, 'Other'), (13, 'Distributions'), (14, 'Investor Reports'), (15, 'Financial Statements'), (16, 'Purchased Agreements'), (17, 'Subscription Documents')]),
        ),
    ]
