# Generated by Django 3.2.10 on 2022-01-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_usernotification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedFundUserNotification',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notifications.usernotification',),
        ),
    ]
