# Generated by Django 3.2.15 on 2022-09-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_usernotification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'New Investment'), (2, 'Capital Call'), (3, 'Purchase Offer'), (4, 'Quarterly Statement'), (5, 'Purchase Confirmation'), (6, 'Prospectus'), (7, 'Agreement'), (8, 'Interest Statement'), (9, 'Nav Statement'), (10, 'Pitch Book'), (11, 'Tax'), (12, 'Other'), (13, 'Distributions'), (14, 'Investor Reports'), (15, 'Financial Statements'), (16, 'Purchased Agreements'), (17, 'Subscription Documents'), (18, 'Financial Information'), (19, 'Property Portfolio'), (20, 'Quarterly Report'), (21, 'Ethics'), (22, 'Investor Meeting Materials'), (23, 'Strategic Materials'), (24, 'Sustainability'), (35, 'Annual Report'), (36, 'Monthly Report')]),
        ),
    ]
