# Generated by Django 3.2.16 on 2023-03-13 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital_calls', '0007_auto_20230313_1001'),
        ('notifications', '0006_alter_usernotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='fund_capital_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_capital_call_notification', to='capital_calls.fundcapitalcall'),
        ),
    ]
