# Generated by Django 3.2.12 on 2022-03-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxform',
            name='form_id',
            field=models.CharField(default=0, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
