# Generated by Django 3.2.12 on 2022-03-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_records', '0002_alter_taxform_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxform',
            name='version',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
