# Generated by Django 3.2.12 on 2022-03-02 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_companyuser_unique_together'),
        ('tax_records', '0003_taxform_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltaxrecord',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='taxrecord',
            name='workflow',
        ),
        migrations.AddField(
            model_name='taxform',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
    ]
