# Generated by Django 3.2.12 on 2022-03-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_companyuser_unique_together'),
        ('tax_records', '0004_auto_20220302_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxform',
            name='form_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='taxform',
            unique_together={('company', 'form_id', 'version')},
        ),
    ]
