# Generated by Django 3.2.12 on 2022-03-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_records', '0007_auto_20220304_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxrecord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
