# Generated by Django 3.2.12 on 2022-03-25 21:51

from django.db import migrations, models
import uuid

def create_uuid(apps, schema_editor):
    Record = apps.get_model('tax_records', 'TaxRecord')
    for record in Record.objects.all():
        record.uuid = uuid.uuid4()
        record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tax_records', '0008_auto_20220304_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltaxrecord',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='taxrecord',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
        ),

    ]
