# Generated by Django 3.2.13 on 2022-07-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0007_auto_20220701_1148'),
        ('tax_records', '0010_auto_20220622_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrecord',
            name='countries',
            field=models.ManyToManyField(to='geographics.Country'),
        ),
    ]
