# Generated by Django 3.2.13 on 2022-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0007_auto_20220701_1148'),
        ('tax_records', '0011_taxrecord_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecord',
            name='countries',
            field=models.ManyToManyField(blank=True, to='geographics.Country'),
        ),
    ]
