# Generated by Django 3.2.15 on 2022-10-06 12:32

from django.db import migrations


def update_self_tax_form_description(apps, schema_editor):
    TaxForm = apps.get_model('tax_records', 'TaxForm')
    TaxForm.objects.filter(form_id='Global-Individual-SC').update(description='Individual Self-Certification')
    TaxForm.objects.filter(form_id='Global-Entity-SC').update(description='Entity Self-Certification')


class Migration(migrations.Migration):
    dependencies = [
        ('tax_records', '0012_alter_taxrecord_countries'),
    ]

    operations = [
        migrations.RunPython(
            update_self_tax_form_description,
            reverse_code=migrations.RunPython.noop
        ),
    ]
