# Generated by Django 3.2.15 on 2022-11-04 16:31

from django.db import migrations


def update_tax_document_uploaded_by(apps, schema_editor):
    TaxDocument = apps.get_model('documents', 'TaxDocument')
    for tax_document in TaxDocument.objects.all():
        if tax_document.document.uploaded_by_user:
            continue

        if not tax_document.document.uploaded_by:
            continue

        tax_document.document.uploaded_by_user = tax_document.document.uploaded_by
        tax_document.document.save()


class Migration(migrations.Migration):
    dependencies = [
        ('tax_records', '0013_auto_20221006_1232'),
    ]

    operations = [
        migrations.RunPython(update_tax_document_uploaded_by, reverse_code=migrations.RunPython.noop)
    ]
