# Generated by Django 3.2.5 on 2021-10-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='full name'),
        ),
    ]
