# Generated by Django 3.2.5 on 2021-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_retailuser_first_login_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailuser',
            name='is_sidecar_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a sidecar admin.', verbose_name='is sidecar admin'),
        ),
    ]
