# Generated by Django 3.2.10 on 2022-01-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_retailuser_is_sidecar_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email address'),
        ),
    ]
