# Generated by Django 3.2.12 on 2022-03-15 19:33
from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from api.admin_users.models import AdminUser
from api.users.constants import REVIEWER_GROUPS, REVIEWER_PERMISSIONS, REVIEWER_GROUP_TO_PERMISSION_CODE_MAP
from django.contrib.auth.models import Group, Permission


def create_groups(apps, schema_editor):
    for g_name in REVIEWER_GROUPS:
        Group.objects.get_or_create(name=g_name)


def delete_groups(apps, schema_editor):
    Group.objects.filter(name__in=REVIEWER_GROUPS).delete()


def create_permissions(apps, schema_editor):
    permissions_to_add = []
    content_type = ContentType.objects.get_for_model(AdminUser)
    for permission_code, permission_name in REVIEWER_PERMISSIONS:
        permissions_to_add.append(
            Permission(
                codename=permission_code,
                name=permission_name,
                content_type=content_type,
            )
        )

    Permission.objects.bulk_create(permissions_to_add)


def delete_permissions(apps, schema_editor):
    permission_codes = [permission_code for permission_code, _ in REVIEWER_PERMISSIONS]
    Permission.objects.filter(codename=permission_codes).delete()


def assign_required_permissions_to_groups(apps, schema_editor):
    for group_name, permission_code in REVIEWER_GROUP_TO_PERMISSION_CODE_MAP.items():
        group = Group.objects.get(name=group_name)
        permissions_to_assign = Permission.objects.get(codename=permission_code)

        group.permissions.add(permissions_to_assign)


def remove_group_permissions(apps, schema_editor):
    pass


def remove_user_group(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_auto_20220210_1248'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=delete_groups),
        migrations.RunPython(create_permissions, reverse_code=delete_permissions),
        migrations.RunPython(assign_required_permissions_to_groups, reverse_code=remove_group_permissions),
    ]
