# Generated by Django 3.2.12 on 2022-03-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220315_1933'),
        ('users', '0008_retailuser_is_invited'),
    ]

    operations = [
    ]
