# Generated by Django 3.2.13 on 2022-06-22 16:38
from django.contrib.auth.models import Group
from django.db import migrations

from api.users.constants import REVIEWER_GROUPS


def create_groups(apps, schema_editor):
    for group_name in REVIEWER_GROUPS:
        Group.objects.get_or_create(name=group_name)


def delete_groups(apps, schema_editor):
    Group.objects.filter(name__in=REVIEWER_GROUPS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0009_merge_20220326_1454'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=delete_groups),
    ]
