# Generated by Django 3.2.16 on 2023-01-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220622_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
