# Generated by Django 3.2.15 on 2023-01-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_retailuser_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailuser',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
