# Generated by Django 3.2.16 on 2023-01-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_retailuser_email'),
        ('users', '0012_alter_retailuser_deleted'),
    ]

    operations = [
    ]
