# Generated by Django 3.2.16 on 2023-03-06 08:34

from api.users.constants import CAPITAL_CALL_REVIEWER
from django.contrib.auth.models import Group
from django.db import migrations


def create_capital_call_groups(apps, schema_editor):
    Group.objects.get_or_create(name=CAPITAL_CALL_REVIEWER)


def delete_capital_call_groups(apps, schema_editor):
    Group.objects.filter(name=CAPITAL_CALL_REVIEWER).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20230112_1921'),
    ]

    operations = [
        migrations.RunPython(create_capital_call_groups, reverse_code=delete_capital_call_groups),
    ]
