# Generated by Django 3.2.16 on 2023-03-14 10:16

from api.users.constants import DISTRIBUTION_NOTICE_REVIEWER
from django.contrib.auth.models import Group
from django.db import migrations


def create_distribution_notice_group(apps, schema_editor):
    Group.objects.get_or_create(name=DISTRIBUTION_NOTICE_REVIEWER)


def delete_distribution_notice_group(apps, schema_editor):
    Group.objects.filter(name=DISTRIBUTION_NOTICE_REVIEWER).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230306_0834'),
    ]

    operations = [
        migrations.RunPython(create_distribution_notice_group, reverse_code=delete_distribution_notice_group),
    ]
