# Generated by Django 3.2.18 on 2023-03-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_historicalretailuser'),
        ('users', '0015_auto_20230314_1016'),
    ]

    operations = [
    ]
