# Generated by Django 3.2.10 on 2021-12-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('analytics', '0001_initial'), ('analytics', '0002_rename_action_entityaction_user_action'), ('analytics', '0003_auto_20211229_0347')]

    dependencies = [
        ('companies', '0008_auto_20211109_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('module', models.IntegerField(choices=[(1, 'Company'), (2, 'Investments')])),
                ('entity', models.IntegerField(choices=[(1, 'Fund')])),
                ('entity_id', models.IntegerField()),
                ('action', models.IntegerField(choices=[(1, 'View Marketing Page'), (2, 'View Indication Of Interest')])),
                ('view_count', models.IntegerField(blank=True, default=0, help_text='The number of times this action has been taken on this entity')),
                ('company', models.ForeignKey(help_text='The company this view belongs to', on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('user', models.ForeignKey(help_text='Which user triggered this view', on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entityaction',
            constraint=models.UniqueConstraint(fields=('module', 'entity', 'entity_id', 'action', 'user'), name='unique_entity_user_action'),
        ),
        migrations.RenameField(
            model_name='entityaction',
            old_name='action',
            new_name='user_action',
        ),
        migrations.RemoveConstraint(
            model_name='entityaction',
            name='unique_entity_user_action',
        ),
        migrations.AddConstraint(
            model_name='entityaction',
            constraint=models.UniqueConstraint(fields=('module', 'entity', 'entity_id', 'user_action', 'user'), name='unique_entity_user_action'),
        ),
    ]
