# Generated by Django 3.2.12 on 2022-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this Admin belongs to. A user will get all permissions granted to each of their groups.', related_name='group_admin_users', related_query_name='admin_user', to='auth.Group', verbose_name='groups'),
        ),
    ]
