# Generated by Django 3.2.13 on 2022-08-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0004_auto_20220727_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='title',
            field=models.CharField(blank=True, default='General Partner Signer', max_length=120, null=True),
        ),
    ]
