# Generated by Django 3.2.15 on 2023-01-03 11:42

from django.db import migrations

from api.users.constants import INTERNAL_TAX_REVIEWER


def create_internal_tax_reviewer_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name=INTERNAL_TAX_REVIEWER)


class Migration(migrations.Migration):
    dependencies = [
        ('admin_users', '0005_adminuser_title'),
    ]

    operations = [
        migrations.RunPython(create_internal_tax_reviewer_group, reverse_code=migrations.RunPython.noop)
    ]
