export enum ILabels {
    bank_country = "Where is your office located?",
    bank_name = "Bank name",
    routing_number = "Routing number",
    swift_code = "Swift/ABA",
    intermediary_bank_name = "Intermediary Bank name",
    intermediary_bank_swift_code = "Intermediary Swift/ABA",
    street_address = "Street address",
    city = "City",
    state = "State",
    province = "Province",
    postal_code = "Postal code",
    account_name = "Account name",
    account_number = "Account number",
    iban_number = "IBAN number",
    credit_account_name = "For further credit account name",
    credit_account_number = "For further credit account number",
    currency = "Currency",
    reference = "Reference",
}