# Generated by Django 3.2.16 on 2023-03-14 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0064_auto_20230320_1138'),
        ('funds', '0053_auto_20230210_1408'),
        ('workflows', '0026_alter_workflow_module'),
        ('companies', '0032_company_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_timestamp', models.DateField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_distribution_notices', to='companies.company')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_distribution_notices', to='funds.fund')),
                ('workflow', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_distribution_notice', to='workflows.workflow')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DistributionNoticeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('investments', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('ownership', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('management_fees', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('organization_cost', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('fund_expenses', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('total_to_date', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('partner_commitment', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('previously_contributed', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('unpaid_commitment', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('distribution_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_notice_details', to='distribution_notices.distributionnotice')),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_notice_detail', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_distribution_notice_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
