# Generated by Django 3.2.16 on 2023-03-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionnotice',
            name='distribution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionnoticedetail',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
