# Generated by Django 3.2.11 on 2022-01-26 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0002_alter_card_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('employer_name', models.TextField(max_length=120, null=True)),
                ('occupation', models.TextField(max_length=120, null=True)),
                ('tax_country', models.TextField(max_length=120, null=True)),
                ('tax_address', models.TextField(max_length=120, null=True)),
                ('tax_city', models.TextField(max_length=120, null=True)),
                ('tax_state', models.TextField(max_length=120, null=True)),
                ('tax_zip', models.TextField(max_length=120, null=True)),
                ('tax_id_number', models.TextField(max_length=120, null=True)),
                ('tax_phone_number', models.TextField(max_length=120, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
