# Generated by Django 3.2.12 on 2022-02-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_auto_20220215_1853'),
        ('companies', '0013_alter_companyuser_unique_together'),
        ('kyc_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrecord',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='employment_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Employed'), (2, 'Unemployed')], null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Submitted'), (3, 'Change Requested'), (4, 'Approved')], default=1),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='employer_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='occupation',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_city',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_country',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_id_number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_phone_number',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_state',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_zip',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='kycrecord',
            unique_together={('user', 'workflow', 'company')},
        ),
        migrations.CreateModel(
            name='HistoricalKYCRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Submitted'), (3, 'Change Requested'), (4, 'Approved')], default=1)),
                ('employment_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Employed'), (2, 'Unemployed')], null=True)),
                ('employer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('occupation', models.CharField(max_length=120, null=True)),
                ('tax_country', models.CharField(max_length=120, null=True)),
                ('tax_address', models.CharField(max_length=120, null=True)),
                ('tax_city', models.CharField(max_length=120, null=True)),
                ('tax_state', models.CharField(max_length=120, null=True)),
                ('tax_zip', models.CharField(max_length=120, null=True)),
                ('tax_id_number', models.CharField(max_length=120, null=True)),
                ('tax_phone_number', models.CharField(max_length=120, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='companies.company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cards.workflow')),
            ],
            options={
                'verbose_name': 'historical kyc record',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
