# Generated by Django 3.2.12 on 2022-02-16 20:51

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0002_auto_20211207_0936'),
        ('kyc_records', '0002_auto_20220215_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='gender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='tax_id_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='gender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='tax_id_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='occupation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='tax_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='tax_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='tax_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographics.country'),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='tax_id_number',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='tax_state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='tax_zip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='occupation',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geographics.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_id_number',
            field=encrypted_fields.fields.EncryptedCharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_zip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
