# Generated by Django 3.2.12 on 2022-02-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0003_auto_20220216_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
