# Generated by Django 3.2.12 on 2022-02-16 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0002_auto_20211207_0936'),
        ('kyc_records', '0004_auto_20220216_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycrecord',
            name='tax_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geographics.country'),
        ),
    ]
