# Generated by Django 3.2.12 on 2022-02-25 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0004_alter_countryiddocumenttype_id_document_type'),
        ('kyc_records', '0006_auto_20220225_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='citizenship_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographics.country'),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='id_document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Passport'), (2, "Driver's license"), (3, 'SSN card'), (4, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='citizenship_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizenship_country', to='geographics.country'),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='id_document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Passport'), (2, "Driver's license"), (3, 'SSN card'), (4, 'Other')], null=True),
        ),
    ]
