# Generated by Django 3.2.12 on 2022-02-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0007_auto_20220225_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='id_document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Passport'), (2, "Driver's license"), (3, 'SSN card'), (4, 'National ID card'), (5, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='id_document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Passport'), (2, "Driver's license"), (3, 'SSN card'), (4, 'National ID card'), (5, 'Other')], null=True),
        ),
    ]
