# Generated by Django 3.2.12 on 2022-03-01 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0005_alter_countryiddocumenttype_id_document_type'),
        ('kyc_records', '0008_auto_20220228_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='eligibility_country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographics.country'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='eligibility_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_country', to='geographics.country'),
        ),
    ]
