# Generated by Django 3.2.12 on 2022-03-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0010_auto_20220303_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
