# Generated by Django 3.2.12 on 2022-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0011_auto_20220307_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='department',
            field=models.CharField(blank=True, choices=[('accounting', 'Accounting'), ('admin', 'Admin'), ('management', 'Management'), ('hr', 'HR')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='job_band',
            field=models.CharField(blank=True, choices=[('M5', 'M5'), ('M4', 'M4'), ('M3', 'M3'), ('M2', 'M2')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='department',
            field=models.CharField(blank=True, choices=[('accounting', 'Accounting'), ('admin', 'Admin'), ('management', 'Management'), ('hr', 'HR')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='job_band',
            field=models.CharField(blank=True, choices=[('M5', 'M5'), ('M4', 'M4'), ('M3', 'M3'), ('M2', 'M2')], max_length=2, null=True),
        ),
    ]
