# Generated by Django 3.2.12 on 2022-03-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0013_auto_20220316_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='job_band',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='job_band',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
