# Generated by Django 3.2.12 on 2022-03-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0014_auto_20220317_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkycrecord',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='historicalkycrecord',
            name='home_id_number',
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='home_id_number',
        ),
    ]
