# Generated by Django 3.2.12 on 2022-03-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0016_auto_20220318_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkycrecord',
            name='authorized_signatories',
        ),
        migrations.RemoveField(
            model_name='historicalkycrecord',
            name='current_directors_managers',
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='authorized_signatories',
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='current_directors_managers',
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='kyc_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_participants', to='kyc_records.kycrecord'),
        ),
    ]
