# Generated by Django 3.2.12 on 2022-03-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0017_auto_20220322_1857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kycrecord',
            unique_together=set(),
        ),
    ]
