# Generated by Django 3.2.12 on 2022-03-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0018_alter_kycrecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='general_partnership_is_a_private_company',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='general_partnership_is_a_private_company',
            field=models.BooleanField(null=True),
        ),
    ]
