# Generated by Django 3.2.12 on 2022-03-25 21:51

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    KycRecord = apps.get_model('kyc_records', 'KYCRecord')
    for record in KycRecord.objects.all():
        record.uuid = uuid.uuid4()
        record.save()


class Migration(migrations.Migration):
    dependencies = [
        ('kyc_records', '0018_alter_kycrecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='kycrecord',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
        ),
    ]
