# Generated by Django 3.2.12 on 2022-03-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0017_auto_20220323_2015'),
        ('kyc_records', '0018_alter_kycrecord_unique_together'),
        ('kyc_records', '0019_auto_20220324_0017'),
    ]

    operations = [
    ]
