# Generated by Django 3.2.12 on 2022-03-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0019_auto_20220325_2151'),
        ('kyc_records', '0020_merge_20220326_1453'),
    ]

    operations = [
    ]
