# Generated by Django 3.2.12 on 2022-03-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0021_auto_20220331_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='source_of_wealth',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='source_of_wealth',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
