# Generated by Django 3.2.12 on 2022-04-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0021_merge_20220329_1809'),
        ('kyc_records', '0022_auto_20220331_2118'),
    ]

    operations = [
    ]
