# Generated by Django 3.2.12 on 2022-04-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0014_workflow_sub_module'),
        ('kyc_records', '0023_merge_20220404_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='review_workflow',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='review_workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_kyc_record', to='workflows.workflow'),
        ),
    ]
