# Generated by Django 3.2.12 on 2022-04-17 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0005_alter_countryiddocumenttype_id_document_type'),
        ('kyc_records', '0023_merge_20220404_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='date_of_incorporation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographics.country'),
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='nature_of_business',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='registered_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='date_of_incorporation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_of_incorporation', to='geographics.country'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='nature_of_business',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='registered_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='kyc_investor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individual'), (2, 'Participant'), (3, 'ENTITY'), (4, 'Private Company'), (5, 'Limited Partnership')], default=1),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='kyc_investor_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Individual'), (2, 'Participant'), (3, 'ENTITY'), (4, 'Private Company'), (5, 'Limited Partnership')], default=1),
        ),
    ]
