# Generated by Django 3.2.12 on 2022-04-05 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0002_adminuser_groups'),
        ('kyc_records', '0024_auto_20220404_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCRiskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('risk_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('kyc_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_value_kyc', to='kyc_records.kycrecord')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_users.adminuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
