# Generated by Django 3.2.13 on 2022-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0024_auto_20220412_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='is_lasalle_or_jll_employee',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='pollitically_exposed_person',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='purpose_of_the_subscription',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='purpose_of_the_subscription_other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='is_lasalle_or_jll_employee',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='pollitically_exposed_person',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='purpose_of_the_subscription',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='purpose_of_the_subscription_other',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
