# Generated by Django 3.2.13 on 2022-04-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0025_auto_20220405_1151'),
        ('kyc_records', '0025_auto_20220413_1901'),
    ]

    operations = [
    ]
