# Generated by Django 3.2.12 on 2022-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0026_auto_20220421_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='one_director',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='one_director',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
