# Generated by Django 3.2.13 on 2022-04-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0025_auto_20220413_1901'),
        ('kyc_records', '0027_auto_20220421_1325'),
    ]

    operations = [
    ]
