# Generated by Django 3.2.13 on 2022-04-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0026_merge_0025_auto_20220405_1151_0025_auto_20220413_1901'),
        ('kyc_records', '0028_merge_0025_auto_20220413_1901_0027_auto_20220421_1325'),
    ]

    operations = [
    ]
