# Generated by Django 3.2.13 on 2022-06-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0005_alter_countryiddocumenttype_id_document_type'),
        ('kyc_records', '0029_merge_20220425_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='where_were_you_when_you_decided_to_invest',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographics.country'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='where_were_you_when_you_decided_to_invest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='where_were_you_when_you_decided_to_invest', to='geographics.country'),
        ),
    ]
