# Generated by Django 3.2.13 on 2022-06-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0030_auto_20220617_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalkycrecord',
            name='economic_beneficiary_other',
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='economic_beneficiary_other',
        ),
        migrations.AddField(
            model_name='historicalkycrecord',
            name='source_of_funds_sale',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='source_of_funds_sale',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
