# Generated by Django 3.2.13 on 2022-06-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0005_alter_countryiddocumenttype_id_document_type'),
        ('kyc_records', '0030_auto_20220603_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalkycrecord',
            old_name='where_were_you_when_you_decided_to_invest',
            new_name='investor_location',
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='where_were_you_when_you_decided_to_invest',
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='investor_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_location', to='geographics.country'),
        ),
    ]
