# Generated by Django 3.2.13 on 2022-06-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0031_auto_20220617_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalkycrecord',
            old_name='date_of_incorporation',
            new_name='date_of_formation',
        ),
        migrations.RenameField(
            model_name='kycrecord',
            old_name='date_of_incorporation',
            new_name='date_of_formation',
        ),
    ]
