# Generated by Django 3.2.13 on 2022-06-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0006_usstates'),
        ('kyc_records', '0032_auto_20220619_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='jurisdiction_state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographics.usstate'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='jurisdiction_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jurisdiction_state', to='geographics.usstate'),
        ),
    ]
