# Generated by Django 3.2.13 on 2022-06-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0030_auto_20220616_1627'),
        ('kyc_records', '0033_auto_20220619_1701'),
    ]

    operations = [
    ]
