# Generated by Django 3.2.13 on 2022-06-22 13:26

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0035_auto_20220622_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='phone_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='phone_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
    ]
