# Generated by Django 3.2.13 on 2022-06-23 21:09

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0036_auto_20220622_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='economic_beneficiary',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='source_of_funds_other',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='source_of_funds_sale',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='economic_beneficiary',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='source_of_funds_other',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='source_of_funds_sale',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
    ]
