# Generated by Django 3.2.13 on 2022-06-28 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0031_auto_20220615_1821'),
        ('kyc_records', '0037_auto_20220623_2109'),
    ]

    operations = [
    ]
