# Generated by Django 3.2.13 on 2022-07-21 13:06

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0039_auto_20220707_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='number_of_id',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='number_of_id',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
