# Generated by Django 3.2.13 on 2022-07-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0040_auto_20220720_1013'),
        ('kyc_records', '0040_auto_20220721_1306'),
    ]

    operations = [
    ]
