# Generated by Django 3.2.13 on 2022-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0041_merge_0040_auto_20220720_1013_0040_auto_20220721_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='home_region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='home_region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
