# Generated by Django 3.2.13 on 2022-09-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0042_auto_20220727_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='is_us_citizen',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='is_us_citizen',
            field=models.BooleanField(null=True),
        ),
    ]
