# Generated by Django 3.2.15 on 2022-09-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0042_auto_20220727_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='job_band',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historicalkycrecord',
            name='job_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='job_band',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='job_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
