# Generated by Django 3.2.15 on 2022-09-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0043_auto_20220904_0931'),
        ('kyc_records', '0043_auto_20220907_1354'),
    ]

    operations = [
    ]
