# Generated by Django 3.2.15 on 2022-11-04 08:16

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0044_merge_0043_auto_20220904_0931_0043_auto_20220907_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='entity_title',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='entity_title',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=120, null=True),
        ),
    ]
