# Generated by Django 3.2.16 on 2022-11-11 00:16

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0045_auto_20221104_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='source_of_funds_profession',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='source_of_funds_profession',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
    ]
