# Generated by Django 3.2.13 on 2023-03-27 10:09

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_records', '0046_auto_20221111_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='uk_national_insurance_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='uk_national_insurance_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
