# Generated by Django 3.2.18 on 2023-05-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentdetail_deleted'),
        ('kyc_records', '0047_auto_20230327_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalkycrecord',
            name='payment_detail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payments.paymentdetail'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='payment_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_payment_details', to='payments.paymentdetail'),
        ),
    ]
