# Generated by Django 3.2.18 on 2023-05-23 10:53

from django.db import migrations


def update_kyc_record(apps, schema_editor):
    Application = apps.get_model('applications', 'Application')
    RetailUser = apps.get_model('users', 'RetailUser')

    for user in RetailUser.objects.all():
        applications = Application.objects.filter(
            payment_detail__isnull=False,
            user=user,
        ).distinct('kyc_record').order_by('kyc_record', '-created_at')
        for application in applications:
            kyc_record = application.kyc_record
            if not kyc_record:
                continue
            kyc_record.payment_detail = application.payment_detail
            kyc_record.save(update_fields=['payment_detail'])


def reverse_update_kyc_record(apps, schema_editor):
    KYCRecord = apps.get_model('kyc_records', 'KYCRecord')
    KYCRecord.objects.update(payment_detail=None)


class Migration(migrations.Migration):
    dependencies = [
        ('kyc_records', '0048_auto_20230518_0931'),
    ]

    operations = [
        migrations.RunPython(update_kyc_record, reverse_code=reverse_update_kyc_record)
    ]
