# Generated by Django 3.2.5 on 2021-09-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('partner_id', models.CharField(db_index=True, max_length=250, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.CharField(db_index=True, max_length=120, unique=True)),
                ('fund_type', models.PositiveSmallIntegerField(choices=[(1, 'Open End, Private Equity'), (2, 'Closed End, Private Equity')])),
                ('region_country', models.PositiveSmallIntegerField(choices=[(1, 'Americas'), (2, 'APAC'), (3, 'US'), (4, 'Europe')], default=3)),
                ('risk_profile', models.PositiveSmallIntegerField(choices=[(1, 'Opportunistic')], default=1)),
                ('demand', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('unsold', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('sold', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('existing_investors', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('county_code', models.CharField(blank=True, max_length=3, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('application_period_start_date', models.DateField(blank=True, null=True)),
                ('application_period_end_date', models.DateField(blank=True, null=True)),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('anticipated_first_call_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.FloatField(blank=True, null=True)),
                ('leverage_ratio', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_funds', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_funds', to='companies.companyuser')),
                ('fund_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_funds', to='currencies.currency')),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_funds', to='companies.companyuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
