# Generated by Django 3.2.5 on 2021-09-27 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companytoken'),
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('nav', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('as_of', models.DateField(db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_navs', to='companies.company')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_navs', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
