# Generated by Django 3.2.5 on 2021-10-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_fundnav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='region_country',
        ),
        migrations.AddField(
            model_name='fund',
            name='business_line',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Americas Private'), (2, 'Asia Pacific Private'), (3, 'Europe Private'), (4, 'Global Partner Solutions'), (5, 'Global Securities')], null=True),
        ),
    ]
