# Generated by Django 3.2.5 on 2021-10-11 20:03

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    Fund = apps.get_model('funds', 'Fund')
    for fund in Fund.objects.all():
        fund.investment_product_code = uuid.uuid4().hex
        fund.save()


class Migration(migrations.Migration):
    dependencies = [
        ('funds', '0003_auto_20211011_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='investment_product_code',
            field=models.CharField(db_index=True, max_length=250, blank=True, null=True),
        ),
        migrations.RunPython(create_uuid)
    ]
