# Generated by Django 3.2.5 on 2021-11-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_alter_fund_investment_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('fund_type', models.PositiveSmallIntegerField(choices=[(1, 'Open End, Private Equity'), (2, 'Closed End, Private Equity')])),
                ('business_line', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Americas Private'), (2, 'Asia Pacific Private'), (3, 'Europe Private'), (4, 'Global Partner Solutions'), (5, 'Global Securities')], null=True)),
                ('risk_profile', models.PositiveSmallIntegerField(choices=[(1, 'Opportunistic')], default=1)),
                ('target_size', models.CharField(max_length=250)),
                ('target_investment_markets', models.CharField(max_length=250)),
                ('target_return', models.CharField(max_length=250)),
                ('employee_investment_period', models.CharField(max_length=250)),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_profile', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
