# Generated by Django 3.2.5 on 2021-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_fundprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundprofile',
            name='business_line',
        ),
        migrations.RemoveField(
            model_name='fundprofile',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='fundprofile',
            name='fund_type',
        ),
        migrations.RemoveField(
            model_name='fundprofile',
            name='risk_profile',
        ),
        migrations.AddField(
            model_name='fundprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundprofile',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundprofile',
            name='investment_region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
