# Generated by Django 3.2.5 on 2021-11-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_auto_20211111_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundprofile',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund'),
        ),
    ]
