# Generated by Django 3.2.5 on 2021-11-11 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0008_fundprofile_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundprofile',
            name='fund',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_profile', to='funds.fund'),
        ),
    ]
