# Generated by Django 3.2.5 on 2021-11-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_alter_fundprofile_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='minimum_investment',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13),
        ),
    ]
