# Generated by Django 3.2.5 on 2021-11-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0010_auto_20211111_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundprofile',
            name='allocation_request_dates',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
