# Generated by Django 3.2.5 on 2021-11-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_fundprofile_allocation_request_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundprofile',
            name='eligibility_criteria',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
