# Generated by Django 3.2.5 on 2021-11-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0013_fundinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinterest',
            name='interest_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
