# Generated by Django 3.2.5 on 2021-11-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0014_fundinterest_interest_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='raw_investment_product_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='vehicle_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
