# Generated by Django 3.2.5 on 2021-12-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0015_auto_20211124_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='investment_product_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
