# Generated by Django 3.2.10 on 2022-01-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0016_alter_fund_investment_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
