# Generated by Django 3.2.10 on 2022-01-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0017_fund_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedFund',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('funds.fund',),
        ),
    ]
