# Generated by Django 3.2.11 on 2022-01-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0018_publishedfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
    ]
