# Generated by Django 3.2.10 on 2022-01-18 08:50

from django.db import migrations


def set_created_by_null(apps, schema_editor):
    Fund = apps.get_model('funds', 'Fund')
    Fund.objects.update(created_by=None)


class Migration(migrations.Migration):
    dependencies = [
        ('funds', '0018_publishedfund'),
    ]

    operations = [
        migrations.RunPython(set_created_by_null)
    ]
