# Generated by Django 3.2.11 on 2022-01-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0019_fund_is_legacy'),
        ('funds', '0020_alter_fund_created_by'),
    ]

    operations = [
    ]
