# Generated by Django 3.2.11 on 2022-01-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0017_auto_20211230_2056'),
        ('funds', '0021_merge_0019_fund_is_legacy_0020_alter_fund_created_by'),
    ]

    operations = [
    ]
