# Generated by Django 3.2.12 on 2022-02-19 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0002_auto_20211207_0936'),
        ('funds', '0022_merge_20220125_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='domicile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_funds', to='geographics.country'),
        ),
    ]
