# Generated by Django 3.2.12 on 2022-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0023_fund_domicile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='firm_co_investment_commitment',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='target_fund_size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True),
        ),
    ]
