# Generated by Django 3.2.12 on 2022-03-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0024_auto_20220303_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='focus_region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='fund_page',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='investment_period',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='is_invite_only',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='offer_leverage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='demand',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Open End, Private Equity'), (2, 'Closed End, Private Equity')], null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='minimum_investment',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='risk_profile',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Opportunistic')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='unsold',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=13, null=True),
        ),
    ]
