# Generated by Django 3.2.12 on 2022-03-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0025_auto_20220321_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='risk_profile',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
