# Generated by Django 3.2.12 on 2022-04-13 17:19

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0026_alter_fund_risk_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='status',
            field=django_fsm.FSMIntegerField(blank=True, choices=[(1, 'Publish Opportunity'), (2, 'Accept Applications'), (3, 'Publish Investment Details')], null=True, verbose_name='Task Status'),
        ),
    ]
