# Generated by Django 3.2.13 on 2022-04-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20220404_1635'),
        ('funds', '0026_alter_fund_risk_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundDocumentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_document_Responses', to='funds.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_document_responses', to='companies.companyuser')),
            ],
            options={
                'unique_together': {('fund', 'user')},
            },
        ),
    ]
