# Generated by Django 3.2.12 on 2022-04-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0027_fund_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='status',
        ),
        migrations.AddField(
            model_name='fund',
            name='accept_applications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fund',
            name='publish_investment_details',
            field=models.BooleanField(default=False),
        ),
    ]
