# Generated by Django 3.2.13 on 2022-04-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0028_auto_20220418_1717'),
        ('funds', '0029_fund_is_finalized'),
    ]

    operations = [
    ]
