# Generated by Django 3.2.13 on 2022-04-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0021_auto_20220427_1841'),
        ('companies', '0015_companyfundvehicle'),
        ('funds', '0029_fund_is_finalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundShareClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=120)),
                ('legal_name', models.CharField(max_length=120)),
                ('leverage', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_share_fund_classes', to='companies.company')),
                ('company_fund_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_vehicle_share_classes', to='companies.companyfundvehicle')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FundVehicle',
        ),
    ]
