# Generated by Django 3.2.13 on 2022-04-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0030_auto_20220427_1841'),
        ('funds', '0030_merge_0028_auto_20220418_1717_0029_fund_is_finalized'),
    ]

    operations = [
    ]
