# Generated by Django 3.2.13 on 2022-07-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0002_adminuser_groups'),
        ('funds', '0031_merge_20220427_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='gp_signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_signer', to='admin_users.adminuser'),
        ),
    ]
