# Generated by Django 3.2.13 on 2022-08-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0032_fund_gp_signer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='gp_signer',
        ),
    ]
