# Generated by Django 3.2.15 on 2022-08-16 06:53

import api.libs.utils.nanoid_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0035_auto_20220816_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='external_id',
            field=models.CharField(default=api.libs.utils.nanoid_generator.generate_nanoid, max_length=14, unique=True),
        ),
    ]
