# Generated by Django 3.2.15 on 2022-08-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0036_alter_fund_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='slug',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
