# Generated by Django 3.2.13 on 2022-10-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0037_alter_fund_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='close_applications',
            field=models.BooleanField(default=False),
        ),
    ]
