# Generated by Django 3.2.15 on 2022-10-03 09:32

from django.db import migrations

from api.funds.services.reprocess_fund_documents import ProcessFundFilesRegions


def populate_application_regions(apps, schema_editor):
    ProcessFundFilesRegions(apps=apps).process()


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0038_fund_close_applications'),
    ]

    operations = [
        migrations.RunPython(
            populate_application_regions,
            reverse_code=migrations.RunPython.noop
        ),
    ]
