# Generated by Django 3.2.16 on 2022-12-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0040_alter_fund_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundnav',
            name='nav',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
