# Generated by Django 3.2.16 on 2022-12-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0041_alter_fundnav_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundnav',
            name='nav',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=21),
        ),
    ]
