# Generated by Django 3.2.16 on 2023-01-04 21:14

import api.funds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0042_alter_fundnav_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='investment_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.funds.models.fund_logo_upload_path),
        ),
    ]
