# Generated by Django 3.2.16 on 2023-01-04 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_company_sso_domains'),
        ('funds', '0043_auto_20230104_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(db_index=True, max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_fund_tags', to='companies.company')),
            ],
            options={
                'unique_together': {('slug', 'company')},
            },
        ),
        migrations.AddField(
            model_name='fund',
            name='tags',
            field=models.ManyToManyField(to='funds.FundTag'),
        ),
    ]
