# Generated by Django 3.2.16 on 2023-01-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0044_auto_20230104_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='tags',
            field=models.ManyToManyField(null=True, to='funds.FundTag'),
        ),
    ]
