# Generated by Django 3.2.16 on 2023-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0045_alter_fund_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='tags',
            field=models.ManyToManyField(blank=True, to='funds.FundTag'),
        ),
    ]
