# Generated by Django 3.2.13 on 2023-01-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0046_alter_fund_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='is_nav_disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
