# Generated by Django 3.2.15 on 2023-01-18 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_auto_20230106_0133'),
        ('funds', '0047_fund_is_nav_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundInterestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('question_type', models.CharField(max_length=250)),
                ('options', models.JSONField(default=list)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_interest_questions', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundInterestUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_interest_question_answers', to='funds.fundinterestquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interest_answer', to='companies.companyuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
