# Generated by Django 3.2.16 on 2023-01-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0047_fund_is_nav_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_onboarding', to='funds.fund')),
            ],
            options={
                'db_table': 'external_onboardings',
            },
        ),
    ]
