# Generated by Django 3.2.13 on 2023-01-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_auto_20230106_0133'),
        ('funds', '0047_fund_is_nav_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundIndicationOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_indication_of_interest', to='funds.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
