# Generated by Django 3.2.13 on 2023-01-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0048_fundindicationofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='open_for_indication_interest',
            field=models.BooleanField(default=False),
        ),
    ]
