# Generated by Django 3.2.13 on 2023-01-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0048_fundinterestquestion_fundinterestuseranswer'),
        ('funds', '0049_fund_open_for_indication_interest'),
    ]

    operations = [
    ]
