# Generated by Django 3.2.16 on 2023-01-31 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0048_externalonboarding'),
        ('funds', '0050_merge_20230119_0633'),
    ]

    operations = [
    ]
