# Generated by Django 3.2.16 on 2023-02-10 14:08

import api.funds.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0031_auto_20230129_1600'),
        ('funds', '0051_merge_20230131_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='stats_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='strategy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='target_irr',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='FundManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=api.funds.models.fund_manager_profile_image_path)),
                ('designation', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_fund_managers', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fund',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='fund_managers', to='funds.FundManager'),
        ),
    ]
