# Generated by Django 3.2.16 on 2023-02-10 14:08

import api.funds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0052_auto_20230210_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.funds.models.fund_banner_upload_path),
        ),
        migrations.AddField(
            model_name='fund',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
