# Generated by Django 3.2.18 on 2023-03-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0053_auto_20230210_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='document_filter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
