# Generated by Django 3.2.16 on 2023-03-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0053_auto_20230210_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='enable_internal_tax_flow',
            field=models.BooleanField(default=False),
        ),
    ]
