# Generated by Django 3.2.16 on 2023-04-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0054_fund_document_filter'),
        ('funds', '0054_fund_enable_internal_tax_flow'),
    ]

    operations = [
    ]
