# Generated by Django 3.2.16 on 2023-04-14 12:55

from django.db import migrations, models


def code(apps, schema_editor):
    DocumentFilter = apps.get_model('funds', 'DocumentFilter')
    filters = DocumentFilter.objects.filter(code=None)
    for document_filter in filters:
        document_filter.delete()


def reverse_code():
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0056_auto_20230403_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfilter',
            name='code',
            field=models.TextField(max_length=1000),
        ),
        migrations.RunPython(code, reverse_code)
    ]
