# Generated by Django 3.2.18 on 2023-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0056_auto_20230403_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='skip_tax',
            field=models.BooleanField(default=False),
        ),
    ]
