# Generated by Django 3.2.18 on 2023-05-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0057_alter_documentfilter_code'),
        ('funds', '0057_auto_20230507_1931'),
    ]

    operations = [
    ]
