# Generated by Django 3.2.5 on 2021-10-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyuser_partner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='partner_id',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together={('company', 'partner_id')},
        ),
    ]
