# Generated by Django 3.2.5 on 2021-11-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20211109_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytoken',
            name='display_on_top',
        ),
        migrations.AddField(
            model_name='companyfaq',
            name='display_on_top',
            field=models.BooleanField(default=False),
        ),
    ]
