# Generated by Django 3.2.10 on 2022-01-17 15:33

from django.db import migrations
from slugify import slugify


def create_company_slug(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    for company in Company.objects.all():
        company.slug = slugify(company.name)
        company.save()


class Migration(migrations.Migration):
    dependencies = [
        ('companies', '0010_company_slug'),
    ]

    operations = [
        migrations.RunPython(create_company_slug),
    ]
