# Generated by Django 3.2.10 on 2022-01-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20220117_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
