# Generated by Django 3.2.10 on 2022-01-17 21:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0012_alter_company_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together={('company', 'partner_id'), ('company', 'user')},
        ),
    ]
