# Generated by Django 3.2.12 on 2022-04-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographics', '0005_alter_countryiddocumenttype_id_document_type'),
        ('companies', '0013_alter_companyuser_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='department',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='job_band',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geographics.country'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='region',
            field=models.CharField(blank=True, max_length=250, null=True),
        )
    ]
