# Generated by Django 3.2.13 on 2022-04-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_auto_20220404_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFundVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_vehicles', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
