# Generated by Django 3.2.13 on 2022-06-08 09:24

from django.db import migrations

from api.companies.models import Company
from core.services.setup_db import SetupDbService


def populate_company(apps, schema_editor):
    admin_emails = ['daniel.oshea@am.jll.com']
    knowledgeable_reviewer_emails = ['daniel.oshea@am.jll.com']
    financial_reviewer_emails = ['daniel.oshea@am.jll.com']
    Company.objects.get_or_create(
        slug='lasalle',
        defaults={
            'name': 'lasalle'
        }
    )
    # Todo
    # Added the try/except block here since this runs before
    # geographics.usstate is created which causes the migration to fail.
    # This is a temporary fix. Need to come up with a solution for this
    try:
        SetupDbService(
            company_name='lasalle',
            admin_emails=admin_emails,
            knowledgeable_reviewer_emails=knowledgeable_reviewer_emails,
            financial_reviewer_emails=financial_reviewer_emails
        ).process()
    except:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('companies', '0016_auto_20220503_1836'),
        ('admin_users', '0002_adminuser_groups'),
        ('cards', '0011_auto_20220511_0322'),
        ('currencies', '0002_alter_currencyrate_rate_date'),
        ('documents', '0030_historicaldocument'),
        ('eligibility_criteria', '0042_merge_20220425_1419'),
        ('fund_marketing_pages', '0014_fundmarketingpagereviewer'),
        ('funds', '0031_merge_20220427_2052'),
        ('geographics', '0005_alter_countryiddocumenttype_id_document_type'),
        ('investors', '0021_auto_20220427_1841'),
        ('kyc_records', '0029_merge_20220425_1419'),
        ('tax_records', '0009_auto_20220325_2151'),
        ('users', '0009_merge_20220326_1454'),
        ('workflows', '0014_workflow_sub_module'),
        ('notifications', '0004_publishedfundusernotification'),
        ('payments', '0002_auto_20220428_0945'),
    ]

    operations = [
        # migrations.RunPython(
        #     populate_company,
        #     reverse_code=migrations.RunPython.noop
        # ),
    ]
