# Generated by Django 3.2.13 on 2022-06-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_auto_20220608_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='aml_kyc_expiration_in_months',
            field=models.IntegerField(blank=True, default=36, null=True),
        ),
    ]
