# Generated by Django 3.2.13 on 2022-06-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0040_auto_20220629_0812'),
        ('companies', '0018_company_aml_kyc_expiration_in_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='power_of_attorney_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_of_attorney_for_company', to='documents.document'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='power_of_attorney_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_of_attorney_for_user', to='documents.document'),
        ),
    ]
