# Generated by Django 3.2.13 on 2022-07-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_auto_20220629_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
