# Generated by Django 3.2.14 on 2022-08-08 11:09
from django.core.files import File
from django.db import migrations
from slugify import slugify

from api.companies.constants import DEMO_COMPANY_NAME

COMPANY_LOGOS_TO_LOAD = (
    'lasalle',
    'awesome-pe',
    'sidecar'
)


def create_demo_company(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    demo_company_slug = slugify(DEMO_COMPANY_NAME)
    Company.objects.get_or_create(
        slug=demo_company_slug,
        defaults={
            'name': DEMO_COMPANY_NAME
        }
    )


def get_or_create_default_companies(apps, schema_editor):
    """
    This is for the test cases, these companies would already
    be present in the other databases
    """
    Company = apps.get_model('companies', 'Company')
    Company.objects.get_or_create(
        slug='lasalle',
        defaults={
            'name': 'lasalle'
        }
    )
    Company.objects.get_or_create(
        slug='sidecar',
        defaults={
            'name': 'sidecar'
        }
    )


def set_company_logos(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    for company_slug in COMPANY_LOGOS_TO_LOAD:
        company = Company.objects.get(slug=company_slug)
        with open(f'api/companies/data/logos/{company_slug}.svg', 'rb') as logo:
            company.logo = File(logo)
            company.save(update_fields=['logo'])


class Migration(migrations.Migration):
    dependencies = [
        ('companies', '0020_alter_companyuser_department'),
    ]

    operations = [
        migrations.RunPython(create_demo_company, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(get_or_create_default_companies, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(set_company_logos, reverse_code=migrations.RunPython.noop),
    ]
