# Generated by Django 3.2.15 on 2022-08-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_auto_20220811_1006'),
        ('companies', '0022_auto_20220819_1254'),
    ]

    operations = [
    ]
