# Generated by Django 3.2.15 on 2022-09-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_merge_0022_auto_20220811_1006_0022_auto_20220819_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='job_band',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
