# Generated by Django 3.2.15 on 2022-08-22 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0048_funddocument_gp_signer'),
        ('companies', '0023_merge_0022_auto_20220811_1006_0022_auto_20220819_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('required_once', models.BooleanField(default=False)),
                ('require_signature', models.BooleanField(default=False)),
                ('require_wet_signature', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_required_documents', to='companies.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_company_required_documents', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
