# Generated by Django 3.2.15 on 2022-08-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0005_adminuser_title'),
        ('companies', '0024_companydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='gp_signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_document_gp_signer', to='admin_users.adminuser'),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='require_gp_signature',
            field=models.BooleanField(default=False),
        ),
    ]
