# Generated by Django 3.2.15 on 2022-09-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_auto_20220829_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companydocument',
            options={'ordering': ('created_at',)},
        ),
    ]
