# Generated by Django 3.2.15 on 2022-09-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_auto_20220907_1334'),
        ('companies', '0026_alter_companydocument_options'),
    ]

    operations = [
    ]
