# Generated by Django 3.2.16 on 2023-01-06 01:33

from django.db import migrations
from django.db import transaction

from uuid import uuid4
from slugify import slugify

def add_elyplace(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    CompanyUser = apps.get_model('companies', "CompanyUser")
    AdminUser = apps.get_model('admin_users', 'AdminUser')
    RetailUser = apps.get_model('users', 'RetailUser')
    new_company = Company()

    with transaction.atomic():
        # Setup Ely place as a new company
        new_company.name = "Ely Place"
        new_company.slug = slugify(new_company.name)
        new_company.is_enabled = True
        new_company.save()

        # Create new user to be investor and admin
        user = RetailUser()
        user.email = 'do+elyplace@hellosidecar.com'
        user.username = user.email
        user.first_name = 'Daniel'
        user.last_name = "O'Shea"
        user.is_sidecar_admin = True
        user.save()

        # add user to the company we just created
        cu = CompanyUser()
        cu.user = user
        cu.company = new_company
        cu.partner_id = uuid4().hex
        cu.save()

        # add the user as an admin
        au = AdminUser()
        au.user = user
        au.company = new_company
        au.title = "Production Support"
        au.save()



class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_company_sso_domains'),
    ]

    operations = [
        migrations.RunPython(add_elyplace),
    ]
