# Generated by Django 3.2.16 on 2023-01-29 16:00

from django.db import migrations
from django.db import transaction

def set_program_name(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    CompanyProfile = apps.get_model('companies', 'CompanyProfile')

    with transaction.atomic():
        for company in Company.objects.all():
            company_profile, _ = CompanyProfile.objects.get_or_create(company=company)

            if not company_profile.program_name:
                company_profile.program_name = "{} Employee Co-Investment".format(company.name)
                company_profile.save()



class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_auto_20230124_2204'),
    ]

    operations = [
        migrations.RunPython(set_program_name),
    ]
