# Generated by Django 3.2.16 on 2023-03-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0061_auto_20230316_0735'),
        ('companies', '0031_auto_20230129_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('report_date', models.DateField()),
                ('report_type', models.CharField(choices=[('financial_statements', 'Financial Statements'), ('fund_accounting', 'Fund Accounting'), ('due_from_to_investors', 'Due from/to Investors ')], max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reports', to='companies.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_reports', to='documents.document')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_reports', to='companies.companyfundvehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
