# Generated by Django 3.2.18 on 2023-03-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_company_address'),
        ('companies', '0032_companyreportdocument'),
    ]

    operations = [
    ]
