# Generated by Django 3.2.16 on 2023-03-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0033_merge_0032_company_address_0032_companyreportdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreportdocument',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='companyreportdocument',
            name='vehicles',
            field=models.ManyToManyField(related_name='vehicle_reports', to='companies.CompanyFundVehicle'),
        ),
    ]
