# Generated by Django 3.2.18 on 2023-03-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_historicalcompanyuser'),
        ('companies', '0036_auto_20230317_2101'),
    ]

    operations = [
    ]
