# Generated by Django 3.2.18 on 2023-04-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0038_auto_20230410_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('theme', models.JSONField(default=dict)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
