# Generated by Django 3.2.18 on 2023-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0039_companytheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_white_labelled_company',
            field=models.BooleanField(default=False),
        ),
    ]
