# Generated by Django 3.2.5 on 2021-12-17 11:52

import api.fund_marketing_pages.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0008_auto_20211109_1041'),
        ('funds', '0015_auto_20211124_0711'),
        ('documents', '0007_auto_20211209_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundMarketingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('sub_header', models.TextField()),
                ('description', models.TextField()),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=api.fund_marketing_pages.models.fund_marketing_page_background_path)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api.fund_marketing_pages.models.fund_marketing_page_logo_path)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Pending Approval'), (3, 'Approved')], default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.companyuser')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_marketing_pages', to='funds.fund')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestAllocationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('investment_amount', models.DecimalField(decimal_places=3, default=0, max_digits=13)),
                ('fund_marketing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_allocation_criteria', to='fund_marketing_pages.fundmarketingpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestAllocationDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('allocation_criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_documents', to='fund_marketing_pages.requestallocationcriteria')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_allocation_criteria', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundPageDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_fund_pages', to='documents.document')),
                ('fund_marketing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_page_documents', to='fund_marketing_pages.fundmarketingpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('data', models.TextField()),
                ('fund_marketing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_facts', to='fund_marketing_pages.fundmarketingpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('url', models.URLField()),
                ('fund_marketing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_blocks', to='fund_marketing_pages.fundmarketingpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
