# Generated by Django 3.2.5 on 2021-12-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_marketing_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundfact',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundfact',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
