# Generated by Django 3.2.5 on 2021-12-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_marketing_pages', '0002_auto_20211221_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerblock',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='footerblock',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
