# Generated by Django 3.2.5 on 2021-12-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_marketing_pages', '0003_auto_20211221_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestallocationcriteria',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestallocationcriteria',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
