# Generated by Django 3.2.5 on 2021-12-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_document_type'),
        ('fund_marketing_pages', '0004_auto_20211221_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestAllocationDocuments',
            new_name='RequestAllocationDocument',
        ),
    ]
