# Generated by Django 3.2.5 on 2021-12-22 09:42

import api.fund_marketing_pages.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund_marketing_pages', '0005_rename_requestallocationdocuments_requestallocationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('promo_file', models.FileField(upload_to=api.fund_marketing_pages.models.fund_marketing_promo_file_path)),
                ('file_type', models.PositiveSmallIntegerField(choices=[(1, 'Image'), (2, 'Video')])),
                ('fund_marketing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fund_page_promo_files', to='fund_marketing_pages.fundmarketingpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
