# Generated by Django 3.2.5 on 2021-12-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_marketing_pages', '0006_promofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundmarketingpage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundmarketingpage',
            name='sub_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundmarketingpage',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
