# Generated by Django 3.2.5 on 2021-12-23 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20211109_1041'),
        ('fund_marketing_pages', '0007_auto_20211223_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundMarketingPageReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('fund_marketing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_marketing_page_reviewers', to='fund_marketing_pages.fundmarketingpage')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
