# Generated by Django 3.2.5 on 2021-12-23 20:15

import api.fund_marketing_pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_marketing_pages', '0008_fundmarketingpagereviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('icon', models.ImageField(upload_to=api.fund_marketing_pages.models.icon_option_icon_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
