# Generated by Django 3.2.5 on 2021-12-23 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund_marketing_pages', '0009_iconoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerblock',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon_footer_blocks', to='fund_marketing_pages.iconoption'),
        ),
    ]
