# Generated by Django 3.2.10 on 2021-12-27 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund_marketing_pages', '0010_footerblock_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundMarketingPageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fund_marketing_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_contact', to='fund_marketing_pages.fundmarketingpage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
