# Generated by Django 3.2.10 on 2022-01-18 08:51

from django.db import migrations


def set_created_by_null(apps, schema_editor):
    FundMarketingPage = apps.get_model('fund_marketing_pages', 'FundMarketingPage')
    FundMarketingPage.objects.update(created_by=None)


class Migration(migrations.Migration):
    dependencies = [
        ('fund_marketing_pages', '0011_fundmarketingpagecontact'),
    ]

    operations = [
        migrations.RunPython(set_created_by_null)
    ]
