# Generated by Django 3.2.10 on 2022-01-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0001_initial'),
        ('fund_marketing_pages', '0013_auto_20220118_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundMarketingPageReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('fund_marketing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_marketing_page_reviewers', to='fund_marketing_pages.fundmarketingpage')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_users.adminuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
