# Generated by Django 3.2.5 on 2021-12-09 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility_criteria', '0006_auto_20211209_0943'),
        ('documents', '0006_investordocument_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Capital Call'), (2, 'Prospectus'), (3, 'Agreement'), (4, 'Interest Statement'), (5, 'Nav Statement'), (6, 'Pitch Book'), (7, 'Tax'), (8, 'Other'), (9, 'Distributions'), (10, 'Investor Reports'), (11, 'Financial Statements'), (12, 'Purchase Agreements'), (13, 'Subscription Documents'), (14, 'Subscription Documents')], default=2),
        ),
        migrations.CreateModel(
            name='CriteriaBlockDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('criteria_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_block_documents', to='eligibility_criteria.criteriablock')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_criteria_blocks', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
