# Generated by Django 3.2.12 on 2022-02-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20220215_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
