# Generated by Django 3.2.12 on 2022-02-26 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax_records', '0001_initial'),
        ('documents', '0010_taxdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdocument',
            name='form_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tax_records.taxform'),
        ),
        migrations.AddField(
            model_name='taxdocument',
            name='tax_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_documents', to='tax_records.taxrecord'),
        ),
    ]
