# Generated by Django 3.2.12 on 2022-03-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_companyuser_unique_together'),
        ('admin_users', '0001_initial'),
        ('documents', '0010_kycdocument_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access_scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Company'), (2, 'Company')], default=2),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_uploaded_documents', to='admin_users.adminuser'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_uploaded_documents', to='companies.companyuser'),
        ),
    ]
