# Generated by Django 3.2.12 on 2022-03-03 20:33

from django.db import migrations

from api.documents.models import Document


def add_fund_documents_company(apps, schema_editor):
    FundDocument = apps.get_model('documents', 'FundDocument')
    for fund_document in FundDocument.objects.all():
        document = fund_document.document
        if not document.company:
            document.company = fund_document.fund.company
            document.save()


def add_kyc_documents_company(apps, schema_editor):
    KYCDocument = apps.get_model('documents', 'KYCDocument')
    for kyc_document in KYCDocument.objects.all():
        document = kyc_document.document
        if not document.company:
            document.company = kyc_document.kyc_record.company
            document.save()


def update_to_company_scope(apps, schema_editor):
    models_to_update = (
        ('documents', 'FundDocument'),
        ('documents', 'CriteriaBlockDocument'),
        ('fund_marketing_pages', 'RequestAllocationDocument'),
        ('fund_marketing_pages', 'FundPageDocument'),
    )
    for app_name, model_name in models_to_update:
        DocumentLinkedModel = apps.get_model(app_name, model_name)
        for linked_model in DocumentLinkedModel.objects.filter(
                document__access_scope=Document.AccessScopeOptions.USER_ONLY.value
        ):
            document = linked_model.document
            document.access_scope = Document.AccessScopeOptions.COMPANY.value
            document.save()


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0011_auto_20220303_2027'),
        ('fund_marketing_pages', '0014_fundmarketingpagereviewer'),
    ]

    operations = [
        migrations.RunPython(add_fund_documents_company),
        migrations.RunPython(add_kyc_documents_company),
        migrations.RunPython(update_to_company_scope),
    ]
