# Generated by Django 3.2.12 on 2022-03-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20220303_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='access_scope',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Company'), (2, 'User Only'), (3, 'Investor Only')], default=2),
        ),
    ]
