# Generated by Django 3.2.12 on 2022-03-02 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0013_rename_envelop_id_taxdocument_envelope_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdocument',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tax_documents', to='users.retailuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxdocument',
            name='envelope_id',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
