# Generated by Django 3.2.12 on 2022-03-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_kycdocument_deleted'),
        ('documents', '0014_auto_20220302_0354'),
    ]

    operations = [
    ]
