# Generated by Django 3.2.12 on 2022-03-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_merge_20220302_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxdocument',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_document', to='documents.document'),
        ),
    ]
