# Generated by Django 3.2.12 on 2022-03-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_merge_20220302_2012'),
        ('documents', '0015_merge_20220302_2306'),
    ]

    operations = [
    ]
