# Generated by Django 3.2.12 on 2022-03-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_alter_taxdocument_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdocument',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
