# Generated by Django 3.2.12 on 2022-03-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_merge_20220303_2152'),
        ('documents', '0017_taxdocument_deleted'),
    ]

    operations = [
    ]
