# Generated by Django 3.2.12 on 2022-03-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_taxdocument_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdocument',
            name='certificate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signature_certificate', to='documents.document'),
        ),
    ]
