# Generated by Django 3.2.12 on 2022-03-09 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_merge_20220305_0012'),
        ('documents', '0018_taxdocument_certificate'),
    ]

    operations = [
    ]
