# Generated by Django 3.2.12 on 2022-03-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20220305_2104'),
        ('documents', '0019_merge_20220309_0141'),
    ]

    operations = [
    ]
