# Generated by Django 3.2.12 on 2022-03-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20220323_2135'),
        ('documents', '0020_merge_20220315_1610'),
    ]

    operations = [
    ]
