# Generated by Django 3.2.13 on 2022-04-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
