# Generated by Django 3.2.13 on 2022-04-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0018_auto_20220421_0701'),
        ('documents', '0023_alter_document_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddocument',
            name='document_for',
            field=models.ManyToManyField(to='investors.InvestorSharedClass'),
        ),
        migrations.AddField(
            model_name='funddocument',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
