# Generated by Django 3.2.13 on 2022-04-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0018_auto_20220421_0701'),
        ('documents', '0024_auto_20220421_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddocument',
            name='document_for',
            field=models.ManyToManyField(blank=True, to='investors.InvestorSharedClass'),
        ),
    ]
