# Generated by Django 3.2.13 on 2022-04-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_alter_funddocument_document_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funddocument',
            name='document_for',
        ),
    ]
