# Generated by Django 3.2.13 on 2022-04-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0030_auto_20220427_1841'),
        ('documents', '0026_remove_funddocument_document_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddocument',
            name='document_for',
            field=models.ManyToManyField(blank=True, to='funds.FundShareClass'),
        ),
    ]
