# Generated by Django 3.2.13 on 2022-05-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20220512_0847'),
        ('documents', '0027_funddocument_document_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application_document_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_request_document', to='applications.applicationdocumentsrequests')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requested_document', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
