# Generated by Django 3.2.13 on 2022-06-03 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20220503_1836'),
        ('documents', '0030_auto_20220526_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDataProtectionPolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_protection_policy_document', to='documents.document')),
                ('fund', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_data_protection_policy_document', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FundDataProtectionPolicyDocument',
        ),
    ]
