# Generated by Django 3.2.13 on 2022-06-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_auto_20220526_1246'),
        ('documents', '0030_historicaldocument'),
    ]

    operations = [
    ]
