# Generated by Django 3.2.13 on 2022-06-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_merge_0030_auto_20220526_1246_0030_historicaldocument'),
        ('documents', '0032_rename_fund_companydataprotectionpolicydocument_company'),
    ]

    operations = [
    ]
