# Generated by Django 3.2.13 on 2022-06-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_auto_20220614_0648'),
        ('documents', '0035_auto_20220613_1838'),
    ]

    operations = [
    ]
