# Generated by Django 3.2.13 on 2022-06-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_auto_20220603_1751'),
        ('documents', '0036_merge_0031_auto_20220614_0648_0035_auto_20220613_1838'),
    ]

    operations = [
    ]
