# Generated by Django 3.2.13 on 2022-06-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_merge_20220615_1759'),
        ('documents', '0038_auto_20220622_1245'),
    ]

    operations = [
    ]
