# Generated by Django 3.2.13 on 2022-06-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_auto_20220622_1245'),
        ('documents', '0038_auto_20220622_2015'),
    ]

    operations = [
    ]
