# Generated by Django 3.2.13 on 2022-06-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_merge_0038_auto_20220622_1245_0038_auto_20220622_2015'),
        ('documents', '0040_auto_20220629_0812'),
    ]

    operations = [
    ]
