# Generated by Django 3.2.13 on 2022-06-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_merge_20220628_1422'),
        ('documents', '0041_merge_20220629_1626'),
    ]

    operations = [
    ]
