# Generated by Django 3.2.13 on 2022-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0042_merge_20220630_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddocument',
            name='require_signature',
            field=models.BooleanField(default=False),
        ),
    ]
