# Generated by Django 3.2.13 on 2022-07-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0044_auto_20220708_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddocument',
            name='require_gp_signature',
            field=models.BooleanField(default=False),
        ),
    ]
