# Generated by Django 3.2.13 on 2022-07-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0044_auto_20220707_1835'),
        ('documents', '0045_funddocument_require_gp_signature'),
    ]

    operations = [
    ]
