# Generated by Django 3.2.13 on 2022-07-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0045_auto_20220722_0735'),
        ('documents', '0046_merge_20220717_1943'),
    ]

    operations = [
    ]
