# Generated by Django 3.2.13 on 2022-08-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0004_auto_20220727_1451'),
        ('documents', '0047_merge_20220726_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='funddocument',
            name='gp_signer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gp_signer', to='admin_users.adminuser'),
        ),
    ]
