# Generated by Django 3.2.15 on 2022-10-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0051_auto_20220912_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='partner_id',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taxdocument',
            name='partner_id',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
    ]
