# Generated by Django 3.2.15 on 2022-10-07 07:30
import uuid
from django.db import migrations


def add_partner_id_for_tax_documents(apps, schema_editor):
    TaxDocument = apps.get_model('documents', 'TaxDocument')
    for tax_document in TaxDocument.objects.all():
        tax_document.partner_id = uuid.uuid4()
        tax_document.save(update_fields=['partner_id'])


def add_partner_id_for_kyc_documents(apps, schema_editor):
    KYCDocument = apps.get_model('documents', 'KYCDocument')
    for kyc_document in KYCDocument.objects.all():
        kyc_document.partner_id = uuid.uuid4()
        kyc_document.save(update_fields=['partner_id'])


class Migration(migrations.Migration):
    dependencies = [
        ('documents', '0052_auto_20221007_0730'),
    ]

    operations = [
        migrations.RunPython(add_partner_id_for_tax_documents, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_partner_id_for_kyc_documents, reverse_code=migrations.RunPython.noop),
    ]
