# Generated by Django 3.2.15 on 2022-11-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0054_auto_20221007_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
