# Generated by Django 3.2.13 on 2022-12-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0054_auto_20221007_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxdocument',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
