# Generated by Django 3.2.16 on 2022-12-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0055_auto_20221118_0746'),
        ('documents', '0055_taxdocument_approved'),
    ]

    operations = [
    ]
