# Generated by Django 3.2.16 on 2023-01-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0056_auto_20221222_1334'),
        ('documents', '0056_merge_20221228_1533'),
    ]

    operations = [
    ]
