# Generated by Django 3.2.18 on 2023-03-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0061_auto_20230302_0837'),
        ('documents', '0061_auto_20230316_0735'),
    ]

    operations = [
    ]
